-- ============================================================================
-- Viva AI Coach — Zengin Egzersiz Kütüphanesi Seed (Sprint 2)
-- 30+ egzersiz; kas grubu, ikincil kaslar, tempo, öneriler, hatalar, ipuçları,
-- AI notu, medya (YouTube/GIF) ve ev/salon bayrakları. İdempotent (upsert).
-- Ekipman kodları: bodyweight, dumbbell, barbell, kettlebell, band, cable,
--                  machine, pullup_bar.
-- Bu dosya schema.sql sonrası çalıştırılır. seed.sql'deki yiyecekleri tamamlar.
-- ============================================================================

insert into public.exercises
  (name, muscle_group, category, difficulty, equipment, secondary_muscles,
   description, correct_form, tempo, rec_sets, rec_reps, rec_rest_sec,
   common_mistakes, tips, ai_notes, video_url, gif_url, is_home, is_gym)
values
-- ---------------- GÖĞÜS ----------------
('Şınav', 'Göğüs', 'compound', 'beginner', 'bodyweight', array['Omuz','Triceps','Karın'],
 'Vücut ağırlığıyla göğüs, omuz ve triceps çalıştıran temel itiş hareketi.',
 'Eller omuz genişliğinden biraz açık, vücut baştan topuğa düz bir hat. Göğsü yere yaklaştır, dirsekleri ~45° tut.',
 '2-0-1', 3, '8-15', 60,
 array['Belin çökmesi','Dirseklerin çok açılması','Kısmi hareket açıklığı'],
 array['Karnını sıkı tut','Nefesi inişte al, çıkışta ver'],
 'Başlangıç için dizden varyasyonla başlanabilir; hedef tam şınava ilerlemek.',
 'https://www.youtube.com/watch?v=IODxDxX7oi4', null, true, true),

('Bench Press', 'Göğüs', 'compound', 'intermediate', 'barbell', array['Omuz','Triceps'],
 'Barbell ile göğüs kaslarını hedefleyen temel güç hareketi.',
 'Kürek kemiklerini sıkıştır, ayaklar yerde. Barı göğüs ortasına indir, kontrollü it.',
 '2-1-1', 4, '6-10', 120,
 array['Kalçayı sekmeden kaldırmak','Barı boyna indirmek','Bilek bükülmesi'],
 array['Spotter kullan','Kavrama omuzdan biraz geniş'],
 'Güç gelişimi için 6-8 tekrar; hipertrofi için 8-12 tekrar aralığı uygun.',
 'https://www.youtube.com/watch?v=rT7DgCr-3pg', null, false, true),

('Dumbbell Press', 'Göğüs', 'compound', 'beginner', 'dumbbell', array['Omuz','Triceps'],
 'Dumbbell ile göğüs; her kolu bağımsız çalıştırır, denge katar.',
 'Sırt bench''e yaslı, dumbbell''ları göğüs hizasında birleştirmeden it.',
 '2-0-1', 3, '8-12', 90,
 array['Dirsekleri kilitlemek','Aşırı ağırlıkla form bozmak'],
 array['İniş fazını yavaşlat','Bilekleri nötr tut'],
 'Ev veya salonda dengesizlikleri gidermek için idealdir.',
 'https://www.youtube.com/watch?v=VmB1G1K7v94', null, true, true),

-- ---------------- SIRT ----------------
('Barfiks', 'Sırt', 'compound', 'intermediate', 'pullup_bar', array['Biceps','Ön Kol'],
 'Vücut ağırlığıyla sırt genişliği ve biceps çalıştıran çekiş hareketi.',
 'Omuzdan geniş kavra, kürek kemiklerini aşağı-geri çek, çeneyi barın üstüne getir.',
 '2-1-2', 3, '5-10', 90,
 array['Sallanarak momentum','Yarım tekrar','Omuz kaldırma'],
 array['Zorlanınca band desteği kullan','İniş fazını kontrol et'],
 'Yeni başlayanlar için lastik band veya negatif tekrarlar önerilir.',
 'https://www.youtube.com/watch?v=eGo4IYlbE5g', null, true, true),

('Deadlift', 'Sırt', 'compound', 'advanced', 'barbell', array['Kalça','Bacak','Trapez'],
 'Tüm arka zinciri çalıştıran temel güç hareketi.',
 'Bar orta ayağın üzerinde, sırt nötr, kalçayı geri it. Barı bacağa yakın tutarak kalk.',
 '1-0-2', 4, '3-6', 180,
 array['Sırtın yuvarlanması','Barın vücuttan uzaklaşması','Dizle kalkmaya çalışmak'],
 array['Kilit noktasında kalçayı sık','Ağırlığı kademeli artır'],
 'Bel hassasiyeti olanlar formu bir uzmanla kontrol etmeli.',
 'https://www.youtube.com/watch?v=op9kVnSso6Q', null, false, true),

('Lat Pulldown', 'Sırt', 'compound', 'beginner', 'cable', array['Biceps'],
 'Makine ile sırt genişliğini geliştiren çekiş hareketi.',
 'Barı göğse doğru çek, dirsekleri aşağı yönlendir, kürek kemiklerini sık.',
 '2-1-2', 3, '10-12', 75,
 array['Geriye yaslanıp momentum','Boyna çekmek'],
 array['Barfikse hazırlık için harika','Zirvede 1 sn dur'],
 'Barfiks yapamayanlar için progresyon hareketi.',
 'https://www.youtube.com/watch?v=CAwf7n6Luuc', null, false, true),

('Dumbbell Row', 'Sırt', 'compound', 'beginner', 'dumbbell', array['Biceps','Arka Omuz'],
 'Tek kol dumbbell kürek çekişi; sırt kalınlığı için.',
 'Bir diz ve el bench''te, sırt düz. Dumbbell''ı kalçaya doğru çek.',
 '2-1-2', 3, '8-12', 60,
 array['Gövde dönmesi','Omuz kaldırma'],
 array['Dirseği gövdeye yakın tut','Zirvede kürek kemiğini sık'],
 'Ev antrenmanları için mükemmel sırt hareketi.',
 'https://www.youtube.com/watch?v=pYcpY20QaE8', null, true, true),

-- ---------------- BACAK ----------------
('Squat', 'Bacak', 'compound', 'beginner', 'barbell', array['Kalça','Karın'],
 'Bacak ve kalça kaslarını çalıştıran temel bileşik hareket.',
 'Ayaklar omuz genişliğinde, göğüs dik. Kalçayı geri-aşağı, dizler parmak yönünde.',
 '2-0-1', 4, '6-10', 120,
 array['Dizlerin içe düşmesi','Topuğun kalkması','Sırtın yuvarlanması'],
 array['Derinliği kademeli artır','Karnını sık'],
 'Vücut ağırlığı squat ile forma hakim olduktan sonra ağırlık ekle.',
 'https://www.youtube.com/watch?v=ultWZbUMPL8', null, false, true),

('Goblet Squat', 'Bacak', 'compound', 'beginner', 'dumbbell', array['Kalça','Karın'],
 'Tek dumbbell/kettlebell göğüste tutularak yapılan squat; form öğrenmek için ideal.',
 'Ağırlığı göğüs önünde tut, dirsekler içeride. Derin çök, göğsü dik tut.',
 '3-1-1', 3, '10-15', 60,
 array['Öne eğilme','Yetersiz derinlik'],
 array['Evde tek dumbbell ile yapılabilir','Core''u aktif tut'],
 'Başlangıç seviyesi için en güvenli squat varyasyonu.',
 'https://www.youtube.com/watch?v=MeIiIdhvXT4', null, true, true),

('Lunges', 'Bacak', 'compound', 'beginner', 'bodyweight', array['Kalça','Denge'],
 'Tek bacak gücü ve dengeyi geliştiren hareket.',
 'Bir adım öne çık, arka dizi yere yaklaştır, ön diz parmak ucunu geçmesin.',
 '2-0-1', 3, '10-12', 60,
 array['Ön dizin çok öne gitmesi','Gövdenin öne düşmesi'],
 array['Ağırlıksız başla, sonra dumbbell ekle'],
 'Evde ekipmansız yapılabilir; dengesizlikleri giderir.',
 'https://www.youtube.com/watch?v=QOVaHwm-Q6U', null, true, true),

('Leg Press', 'Bacak', 'compound', 'beginner', 'machine', array['Kalça'],
 'Makine ile bacak kaslarını güvenli şekilde çalıştırır.',
 'Ayaklar platformda omuz genişliğinde, dizleri kilitle-me. Kontrollü in ve it.',
 '2-0-1', 3, '10-15', 90,
 array['Dizleri tam kilitlemek','Belin platformdan kalkması'],
 array['Ayak yerleşimini hedefe göre değiştir'],
 'Squat''a alternatif; bel yükünü azaltır.',
 'https://www.youtube.com/watch?v=IZxyjW7MPJQ', null, false, true),

('Romanian Deadlift', 'Bacak', 'compound', 'intermediate', 'barbell', array['Kalça','Sırt'],
 'Arka bacak (hamstring) ve kalça odaklı kalça menteşesi hareketi.',
 'Dizler hafif bükük, kalçayı geri it, barı bacağa yakın indir, hamstring gerilsin.',
 '3-1-1', 3, '8-10', 90,
 array['Sırtın yuvarlanması','Dizin çok bükülmesi'],
 array['Gerginliği hamstringde hisset','Bel nötr kalsın'],
 'Hamstring ve kalça gelişimi için compound seçenek.',
 'https://www.youtube.com/watch?v=jEy_czb3RKA', null, false, true),

-- ---------------- OMUZ ----------------
('Omuz Press', 'Omuz', 'compound', 'intermediate', 'dumbbell', array['Triceps'],
 'Dumbbell veya barbell ile omuz kaslarını çalıştıran itiş.',
 'Dirsekler hafif önde, dumbbell''ları baş üstüne it, beli aşırı yaylandırma.',
 '2-0-1', 3, '8-12', 75,
 array['Belin aşırı yaylanması','Yarım hareket'],
 array['Core''u sık','Ayakta zorlanınca otur'],
 'Omuz sağlığı için kontrollü ve tam açıklıkta çalış.',
 'https://www.youtube.com/watch?v=qEwKCR5JCog', null, true, true),

('Lateral Raise', 'Omuz', 'isolation', 'beginner', 'dumbbell', array[]::text[],
 'Yan omuz (deltoid) izolasyon hareketi; omuz genişliği için.',
 'Hafif dumbbell''ları yanlara omuz hizasına kaldır, dirsekler hafif bükük.',
 '2-0-2', 3, '12-15', 45,
 array['Momentumla savurmak','Çok ağır kullanmak'],
 array['Hafif ağırlık + yüksek tekrar','Zirvede bilekleri kaldırma'],
 'Omuz genişliği görünümü için en etkili izolasyon.',
 'https://www.youtube.com/watch?v=3VcKaXpzqRo', null, true, true),

-- ---------------- KOL ----------------
('Biceps Curl', 'Kol', 'isolation', 'beginner', 'dumbbell', array['Ön Kol'],
 'Dumbbell ile biceps izolasyon hareketi.',
 'Dirsekler gövdeye sabit, dumbbell''ları kontrollü kaldır, zirvede sık.',
 '2-0-2', 3, '10-12', 45,
 array['Dirseğin öne kayması','Gövde sallama'],
 array['İniş fazını yavaşlat','Bilek nötr'],
 'Kol gelişimi için temel izolasyon.',
 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo', null, true, true),

('Triceps Pushdown', 'Kol', 'isolation', 'beginner', 'cable', array[]::text[],
 'Kablo ile triceps izolasyon hareketi.',
 'Dirsekler gövdeye sabit, barı aşağı it, zirvede triceps''i sık.',
 '2-0-2', 3, '10-15', 45,
 array['Dirseğin açılması','Gövdeyle bastırmak'],
 array['Dirsekleri sabit tut','Tam uzatma yap'],
 'Kol arka (triceps) hacmi için etkili.',
 'https://www.youtube.com/watch?v=2-LAMcpzODU', null, false, true),

('Diamond Şınav', 'Kol', 'compound', 'intermediate', 'bodyweight', array['Göğüs','Omuz'],
 'Elleri birleştirerek triceps''i öne çıkaran şınav varyasyonu.',
 'Eller göğüs altında elmas şekli, dirsekleri gövdeye yakın tut.',
 '2-0-1', 3, '8-12', 60,
 array['Dirseklerin açılması','Bel çökmesi'],
 array['Zorlanınca dizden yap'],
 'Evde triceps çalışmak için ekipmansız seçenek.',
 'https://www.youtube.com/watch?v=J0DnG1_S92I', null, true, false),

-- ---------------- KARIN ----------------
('Plank', 'Karın', 'isolation', 'beginner', 'bodyweight', array['Omuz','Sırt'],
 'İzometrik core dayanıklılık hareketi.',
 'Dirsekler omuz altında, vücut düz bir hat, karnı ve kalçayı sık.',
 'izometrik', 3, '30-60 sn', 45,
 array['Kalçanın yükselmesi/çökmesi','Nefes tutmak'],
 array['Kalçayı hafif içe al','Süreyi kademeli artır'],
 'Core stabilizasyonu; bel sağlığını destekler.',
 'https://www.youtube.com/watch?v=pSHjTRCQxIw', null, true, true),

('Mekik', 'Karın', 'isolation', 'beginner', 'bodyweight', array[]::text[],
 'Karın kaslarını çalıştıran temel fleksiyon hareketi.',
 'Dizler bükük, elleri göğüste, omuzları kaldırarak karnı sık.',
 '2-0-1', 3, '15-20', 45,
 array['Boyundan çekmek','Momentum kullanmak'],
 array['Hareketi karından başlat','Kontrollü in'],
 'Karın hacmi için klasik; bel hassasiyetinde crunch tercih et.',
 'https://www.youtube.com/watch?v=1fbU_MkV7NE', null, true, true),

('Bacak Kaldırma', 'Karın', 'isolation', 'intermediate', 'bodyweight', array['Kalça'],
 'Alt karın odaklı bacak kaldırma hareketi.',
 'Sırt yerde, bacakları kontrollü kaldır-indir, beli yere bastır.',
 '2-0-2', 3, '12-15', 45,
 array['Belin yerden kalkması','Sallanmak'],
 array['Zorlanınca dizleri bük','İniş fazını yavaşlat'],
 'Alt karın bölgesini hedefler.',
 'https://www.youtube.com/watch?v=JB2oyawG9KI', null, true, true),

-- ---------------- KALÇA ----------------
('Hip Thrust', 'Kalça', 'compound', 'intermediate', 'barbell', array['Bacak'],
 'Kalça (gluteus) gelişimi için en etkili hareketlerden.',
 'Sırt üst kısmı bench''te, bar kalçada. Kalçayı yukarı it, zirvede sık.',
 '2-1-1', 3, '8-12', 90,
 array['Beli aşırı yaylandırmak','Yarım hareket'],
 array['Zirvede 1 sn dur','Çeneyi hafif içe al'],
 'Kalça şekli ve gücü için birincil hareket.',
 'https://www.youtube.com/watch?v=xDmFkJxPzeM', null, false, true),

('Glute Bridge', 'Kalça', 'isolation', 'beginner', 'bodyweight', array['Bacak'],
 'Ekipmansız kalça köprüsü; başlangıç için ideal.',
 'Sırt yerde, dizler bükük. Kalçayı yukarı it, zirvede sık, kontrollü in.',
 '2-1-1', 3, '12-20', 45,
 array['Beli aşırı kullanmak','Zirvede sıkmamak'],
 array['Evde ekipmansız yapılabilir'],
 'Hip thrust''a hazırlık; masa başı çalışanlar için faydalı.',
 'https://www.youtube.com/watch?v=wPM8icPu6H8', null, true, true),

-- ---------------- KARDİYO ----------------
('Burpee', 'Kardiyo', 'functional', 'advanced', 'bodyweight', array['Göğüs','Bacak','Karın'],
 'Tüm vücudu çalıştıran yüksek yoğunluklu fonksiyonel hareket.',
 'Squat → şınav pozisyonu → şınav → zıpla. Akıcı ve kontrollü tekrarla.',
 'akıcı', 4, '10-15', 60,
 array['Belin çökmesi','Kontrolsüz iniş'],
 array['Tempoyu kondisyonuna göre ayarla'],
 'Yağ yakımı ve kondisyon için etkili; eklem hassasiyetinde alternatif seç.',
 'https://www.youtube.com/watch?v=TU8QYVW0gDU', null, true, true),

('Mountain Climber', 'Kardiyo', 'functional', 'beginner', 'bodyweight', array['Karın','Omuz'],
 'Plank pozisyonunda dizleri değiştirerek yapılan kardiyo + core hareketi.',
 'Plank pozisyonu, dizleri sırayla göğse çek, kalça sabit kalsın.',
 'akıcı', 3, '30-45 sn', 45,
 array['Kalçanın yükselmesi','Omuzların kaymaya başlaması'],
 array['Tempoyu koru','Core''u sık'],
 'Evde ısınma veya HIIT için kullanılabilir.',
 'https://www.youtube.com/watch?v=nmwgirgXLYM', null, true, true),

('Koşu Bandı', 'Kardiyo', 'functional', 'beginner', 'machine', array['Bacak'],
 'Kondisyon ve yağ yakımı için temel kardiyo.',
 'Dik postür, kollar doğal salınım. Eğim ve hızı hedefe göre ayarla.',
 'sabit', 1, '20-40 dk', 0,
 array['Korkuluğa yaslanmak','Aşırı öne eğilmek'],
 array['LISS için düşük tempo uzun süre','HIIT için interval'],
 'Kilo verme döneminde haftalık kardiyo hacmini kademeli artır.',
 'https://www.youtube.com/watch?v=kVnyY17VS9Y', null, false, true),

-- ---------------- MOBİLİZASYON / ESNEME ----------------
('Kedi-Deve', 'Sırt', 'mobility', 'beginner', 'bodyweight', array['Karın'],
 'Omurga mobilitesi için kedi-deve hareketi.',
 'Dört ayak üstünde, nefes alırken belini çukurlaştır, verirken kamburlaştır.',
 'yavaş', 2, '10-12', 30,
 array['Hızlı yapmak','Boyunu zorlamak'],
 array['Nefesle senkronize et','Isınma için ideal'],
 'Antrenman öncesi omurga ısınması ve bel sağlığı için.',
 'https://www.youtube.com/watch?v=kqnua4rHVVA', null, true, true),

('Hamstring Esnetme', 'Bacak', 'stretch', 'beginner', 'bodyweight', array[]::text[],
 'Arka bacak (hamstring) esnekliği için statik esnetme.',
 'Otur, bir bacağı uzat, gövdeyi öne eğ, ayak ucuna uzan. 20-30 sn tut.',
 'statik', 2, '20-30 sn', 20,
 array['Zıplayarak esnetmek','Nefes tutmak'],
 array['Antrenman sonrası uygula','Ağrı sınırında kal'],
 'Esneklik ve toparlanma için; ısınmadan yapılırsa hafif tut.',
 'https://www.youtube.com/watch?v=FQBOZQkQ2sE', null, true, true)

on conflict (name) do update set
  muscle_group      = excluded.muscle_group,
  category          = excluded.category,
  difficulty        = excluded.difficulty,
  equipment         = excluded.equipment,
  secondary_muscles = excluded.secondary_muscles,
  description       = excluded.description,
  correct_form      = excluded.correct_form,
  tempo             = excluded.tempo,
  rec_sets          = excluded.rec_sets,
  rec_reps          = excluded.rec_reps,
  rec_rest_sec      = excluded.rec_rest_sec,
  common_mistakes   = excluded.common_mistakes,
  tips              = excluded.tips,
  ai_notes          = excluded.ai_notes,
  video_url         = excluded.video_url,
  is_home           = excluded.is_home,
  is_gym            = excluded.is_gym;

-- ---- Egzersiz ilişkileri (isimle eşleştirilir) ----
insert into public.exercise_alternatives (exercise_id, alt_exercise_id, relation)
select e.id, a.id, rel.relation::alt_relation
from (values
  ('Bench Press', 'Dumbbell Press', 'alternative'),
  ('Bench Press', 'Şınav',          'home'),
  ('Şınav',       'Dumbbell Press', 'gym'),
  ('Squat',       'Goblet Squat',   'alternative'),
  ('Squat',       'Leg Press',      'similar'),
  ('Squat',       'Lunges',         'home'),
  ('Barfiks',     'Lat Pulldown',   'alternative'),
  ('Lat Pulldown','Barfiks',        'similar'),
  ('Deadlift',    'Romanian Deadlift', 'similar'),
  ('Hip Thrust',  'Glute Bridge',   'home'),
  ('Omuz Press',  'Lateral Raise',  'similar'),
  ('Biceps Curl', 'Barfiks',        'similar'),
  ('Triceps Pushdown', 'Diamond Şınav', 'home'),
  ('Mekik',       'Bacak Kaldırma', 'similar'),
  ('Burpee',      'Mountain Climber','similar')
) as rel(src, dst, relation)
join public.exercises e on e.name = rel.src
join public.exercises a on a.name = rel.dst
on conflict (exercise_id, alt_exercise_id, relation) do nothing;
