-- ============================================================================
-- Viva AI Coach — Genişletilmiş Egzersiz Kütüphanesi (Sprint 9)
-- 38 profesyonel egzersiz; tam zengin alanlar (adım adım, nefes, ROM,
-- regresyon/progresyon, hedef, stabilizatör kaslar, kategori taksonomisi).
-- Idempotent upsert (name). migration 0009 SONRASI çalıştırılır.
-- ============================================================================

insert into public.exercises
  (name, english_name, muscle_group, body_region, movement_type, category, difficulty, equipment, environment, is_home, is_gym, primary_muscles, secondary_muscles, stabilizer_muscles, mobility_focus, rehabilitation_focus, exercise_goal, description, correct_form, instructions, breathing, range_of_motion, tempo, rec_sets, rec_reps, rec_rest_sec, common_mistakes, tips, regressions, progressions, ai_notes, video_url, gif_url, calories, average_duration_sec)
values
  ('Eğik Dumbbell Press', 'Incline Dumbbell Press', 'Göğüs', 'front', 'İtiş', 'compound', 'intermediate', 'dumbbell', 'gym', false, true, array['Üst Göğüs'], array['Ön Omuz','Triceps'], array['Rotator manşet'], '{}', '{}', array['Hipertrofi','Kuvvet'], 'Üst göğsü hedefleyen eğik bench itiş hareketi.', 'Bench''i 30-45° eğ, dumbbell''ları üst göğüs hizasında kontrollü it.', array['Bench''i 30-45° ayarla, kürek kemiklerini geri-aşağı sıkıştır.','Dumbbell''ları göğüs üstünde tut.','Kontrollü indir, üst göğüste gerilim hisset.','Güçlü ama kilitlmeden yukarı it.'], 'İnişte nefes al, itişte ver.', 'Dumbbell göğüs hizasına inmeli, tam gerilim.', '2-1-1', 4, '8-12', 90, array['Çok dik açı (omuz baskısı)','Bel köprüsü kurmak'], array['Bileği nötr tut','Üst göğüse odaklan'], array['Machine incline press','Daha hafif ağırlık'], array['Ağırlık artışı','Tempo yavaşlat (3-1-1)'], 'Üst göğüs geride kalanlar için haftada 1-2 kez ideal.', 'https://www.youtube.com/results?search_query=Incline%20Dumbbell%20Press%20exercise%20proper%20form', null, 8, 300),
  ('Cable Fly', 'Cable Chest Fly', 'Göğüs', 'front', 'İzolasyon', 'isolation', 'beginner', 'cable', 'gym', false, true, array['Göğüs'], array['Ön Omuz'], '{}', '{}', '{}', array['Hipertrofi','Kas dayanıklılığı'], 'Kablo ile sabit gerilimde göğüs izolasyonu.', 'Hafif öne eğil, kolları geniş yaydan göğüs önünde birleştir.', array['Makaraları göğüs hizasına ayarla.','Hafif öne adımla, dirsekler hafif bükük.','Kolları yay çizerek önde birleştir.','Kontrollü geri aç.'], 'Birleştirirken ver, açarken al.', 'Geniş açılış, göğüste tam gerilim.', '2-1-2', 3, '12-15', 60, array['Dirseği tamamen düzeltmek','Aşırı ağırlıkla momentum'], array['Göğsü sık','Hareketi yavaş kontrol et'], array['Pec deck'], array['Tek kol cable fly'], null, 'https://www.youtube.com/results?search_query=Cable%20Chest%20Fly%20exercise%20proper%20form', null, 6, 240),
  ('Dips (Göğüs)', 'Chest Dips', 'Göğüs', 'front', 'İtiş', 'compound', 'advanced', 'bodyweight', 'both', true, true, array['Alt Göğüs'], array['Triceps','Ön Omuz'], array['Kor'], '{}', '{}', array['Kuvvet','Hipertrofi'], 'Vücut ağırlığıyla alt göğüs ve triceps geliştiren itiş.', 'Gövdeyi öne eğ, dirsekleri kontrollü bük, göğsü aşağı indir.', array['Paralel bara çık, kollar düz.','Gövdeyi hafif öne eğ.','Dirsekleri bükerek in.','Göğüsle it, yukarı çık.'], 'İnişte al, itişte ver.', 'Omuz dirsek hizasına kadar in.', null, 3, '6-12', 90, array['Çok derine inip omuz zorlamak','Gövdeyi dik tutmak (triceps''e kayar)'], array['Öne eğil (göğüs)','Kontrollü in'], array['Band destekli dips','Machine dips'], array['Ağırlıklı dips'], null, 'https://www.youtube.com/results?search_query=Chest%20Dips%20exercise%20proper%20form', null, 9, 240),
  ('Barbell Row', 'Bent-Over Barbell Row', 'Sırt', 'back', 'Çekiş', 'compound', 'intermediate', 'barbell', 'gym', false, true, array['Sırt (Lat)','Orta Sırt'], array['Biceps','Arka Omuz'], array['Bel','Kor'], '{}', '{}', array['Kuvvet','Hipertrofi'], 'Sırt kalınlığı için temel bileşik çekiş.', 'Kalçadan öne eğil, sırt düz, barı göbeğe çek.', array['Barı omuz genişliğinde kavra.','Kalçadan öne eğil, sırt nötr.','Barı alt göğüs/göbeğe çek.','Kontrollü indir.'], 'Çekişte ver, inişte al.', 'Tam gerilimden göbeğe temas.', '1-1-2', 4, '6-10', 90, array['Belin yuvarlanması','Momentumla sallanmak'], array['Sırtı düz tut','Dirseği gövdeye yakın çek'], array['Chest-supported row','Dumbbell row'], array['Pendlay row'], 'Bel yükünü azaltmak için göğüs destekli varyanta geçilebilir.', 'https://www.youtube.com/results?search_query=Bent-Over%20Barbell%20Row%20exercise%20proper%20form', null, 8, 300),
  ('Göğüs Destekli Row', 'Chest-Supported Row', 'Sırt', 'back', 'Çekiş', 'compound', 'beginner', 'dumbbell', 'gym', false, true, array['Orta Sırt','Sırt (Lat)'], array['Biceps','Arka Omuz'], '{}', '{}', '{}', array['Hipertrofi'], 'Beli koruyan, sırt izolasyonunu artıran destekli çekiş.', 'Eğik bench''e yüzüstü yaslan, dumbbell''ları dirsekten çek.', array['Eğik bench''e göğsünü yasla.','Dumbbell''ları sarkıt.','Kürek kemiklerini sıkarak çek.','Kontrollü indir.'], 'Çekişte ver.', 'Tam gerilimden sıkışmaya.', null, 4, '10-12', 75, array['Sadece kolla çekmek'], array['Kürekleri sık','Tepede 1 sn dur'], array['Machine row'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Chest-Supported%20Row%20exercise%20proper%20form', null, 7, 260),
  ('Düz Kol Pulldown', 'Straight-Arm Pulldown', 'Sırt', 'back', 'Çekiş', 'isolation', 'beginner', 'cable', 'gym', false, true, array['Sırt (Lat)'], array['Arka Omuz','Triceps (uzun baş)'], '{}', '{}', '{}', array['Hipertrofi','Kas dayanıklılığı'], 'Lat kaslarını izole eden düz kol çekiş.', 'Kolları düz tutarak barı kalçaya doğru yay çiz.', array['Yüksek makarayı kavra.','Hafif öne eğil, kollar düz.','Barı kalçaya doğru indir.','Kontrollü yukarı bırak.'], 'İnişte ver.', 'Baş üstünden kalçaya geniş yay.', null, 3, '12-15', 60, array['Dirseği bükmek'], array['Lat''ı hisset','Yavaş kontrol'], array['Hafif ağırlık'], array['Tek kol'], null, 'https://www.youtube.com/results?search_query=Straight-Arm%20Pulldown%20exercise%20proper%20form', null, 5, 220),
  ('Arnold Press', 'Arnold Press', 'Omuz', 'front', 'İtiş', 'compound', 'intermediate', 'dumbbell', 'gym', false, true, array['Omuz'], array['Triceps','Üst Göğüs'], array['Kor'], '{}', '{}', array['Hipertrofi'], 'Rotasyonlu dumbbell omuz presi; tüm deltoid başlarını çalıştırır.', 'Avuçlar sana dönük başla, iterken bilekleri dışa çevir.', array['Dumbbell''ları göğüs önünde avuç içi sana dönük tut.','İterken bilekleri dışa çevir.','Tepede kollar açık.','Ters yolla in.'], 'İtişte ver.', 'Çene hizasından tam yukarı.', null, 3, '10-12', 75, array['Aşırı bel köprüsü','Çok hızlı rotasyon'], array['Kontrollü dön','Kor sıkı'], array['Nötr dumbbell press'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Arnold%20Press%20exercise%20proper%20form', null, 7, 260),
  ('Cable Lateral Raise', 'Cable Lateral Raise', 'Omuz', 'front', 'İzolasyon', 'isolation', 'beginner', 'cable', 'gym', false, true, array['Yan Omuz'], '{}', '{}', '{}', '{}', array['Hipertrofi'], 'Sabit gerilimle yan omuz izolasyonu.', 'Makaradan kolu yana omuz hizasına kaldır.', array['Alçak makarayı çapraz kavra.','Kolu yana omuz hizasına kaldır.','Tepede kısa dur.','Kontrollü indir.'], 'Kaldırışta ver.', 'Kalçadan omuz hizasına.', null, 3, '12-15', 45, array['Momentumla savurmak','Omuz silkme'], array['Serçe parmak hafif yukarı','Yavaş'], array['Dumbbell lateral raise'], array['Drop set'], null, 'https://www.youtube.com/results?search_query=Cable%20Lateral%20Raise%20exercise%20proper%20form', null, 4, 200),
  ('Face Pull (Omuz)', 'Cable Face Pull', 'Omuz', 'back', 'Çekiş', 'isolation', 'beginner', 'cable', 'gym', false, true, array['Arka Omuz'], array['Orta Trapez','Rotator manşet'], '{}', '{}', '{}', array['Postür','Omuz sağlığı'], 'Arka omuz ve dış rotatorları güçlendiren omuz sağlığı hareketi.', 'Halat makarayı yüze doğru, dirsekler yüksek çek.', array['Halatı göz hizasına ayarla.','Baş parmaklar geriye bakacak kavra.','Yüze doğru, dirsekleri yükselterek çek.','Kontrollü geri bırak.'], 'Çekişte ver.', 'Tam uzanıştan yüz hizasına.', null, 3, '15-20', 45, array['Ağırlığı fazla tutmak'], array['Dirsekleri yüksek tut','Kürekleri sık'], array['Band face pull'], array['Duruş süresi ekle'], 'Bench press hacmini dengelemek için haftada 2-3 kez önerilir.', 'https://www.youtube.com/results?search_query=Cable%20Face%20Pull%20exercise%20proper%20form', null, 4, 200),
  ('Hammer Curl', 'Hammer Curl', 'Kol', 'front', 'Çekiş', 'isolation', 'beginner', 'dumbbell', 'both', true, true, array['Biceps','Brachialis'], array['Önkol'], '{}', '{}', '{}', array['Hipertrofi'], 'Nötr kavrayışla biceps ve önkol geliştiren curl.', 'Avuçlar karşılıklı, dumbbell''ları omuza kaldır.', array['Dumbbell''ları nötr kavra.','Dirsek sabit, yukarı kıvır.','Kısa dur.','Kontrollü indir.'], 'Kaldırışta ver.', 'Tam uzanıştan tam kasılmaya.', null, 3, '10-12', 60, array['Dirsek öne kaçması','Sallanmak'], array['Dirseği sabitle','Yavaş indir'], array['Hafif ağırlık'], array['İncline hammer curl'], null, 'https://www.youtube.com/results?search_query=Hammer%20Curl%20exercise%20proper%20form', null, 4, 200),
  ('Skullcrusher', 'Lying Triceps Extension', 'Kol', 'front', 'İtiş', 'isolation', 'intermediate', 'barbell', 'gym', false, true, array['Triceps'], '{}', '{}', '{}', '{}', array['Hipertrofi','Kuvvet'], 'Yatarak triceps izolasyonu.', 'Barı alına doğru indir, sadece önkolu hareket ettir.', array['Sırtüstü yat, barı göğüs üstünde tut.','Dirsekten bükerek alına indir.','Triceps''le it.','Dirsek sabit.'], 'İnişte al.', 'Alına yakın inişten tam uzanışa.', null, 3, '10-12', 75, array['Dirsek açılması','Ağır yük'], array['Dirseği sabit tut','EZ bar bileğe iyi gelir'], array['Dumbbell skullcrusher'], array['Overhead extension'], null, 'https://www.youtube.com/results?search_query=Lying%20Triceps%20Extension%20exercise%20proper%20form', null, 5, 220),
  ('Barfiks (Chin-up)', 'Chin-Up', 'Kol', 'back', 'Çekiş', 'compound', 'advanced', 'pullup_bar', 'both', true, true, array['Biceps','Sırt (Lat)'], array['Orta Sırt'], array['Kor'], '{}', '{}', array['Kuvvet','Hipertrofi'], 'Ters kavrayış barfiks; biceps ve sırt için güçlü bileşik.', 'Avuçlar sana dönük, çeneyi barın üstüne çek.', array['Bara omuz genişliğinde ters kavra.','Kürekleri geri-aşağı sıkıştır.','Çeneyi barın üstüne çek.','Kontrollü in.'], 'Çekişte ver.', 'Tam sarkıştan çene bar üstüne.', null, 3, '5-10', 90, array['Yarım hareket','Sallanmak'], array['Tam açıl','Kontrollü in'], array['Band destekli','Negatif barfiks'], array['Ağırlıklı chin-up'], null, 'https://www.youtube.com/results?search_query=Chin-Up%20exercise%20proper%20form', null, 9, 240),
  ('Front Squat', 'Front Squat', 'Bacak', 'front', 'Çömelme', 'compound', 'advanced', 'barbell', 'gym', false, true, array['Quadriceps'], array['Kalça','Kor'], array['Üst Sırt','Bilek'], '{}', '{}', array['Kuvvet','Hipertrofi'], 'Barı önde taşıyarak quadriceps ve kor''u vurgulayan squat.', 'Bar ön omuzda, dirsekler yüksek, dik gövdeyle çömel.', array['Barı ön deltoid rafına al, dirsekler yüksek.','Ayaklar omuz genişliğinde.','Dik gövdeyle çömel.','Topuktan it.'], 'İnişte al, kalkışta ver.', 'Uyluk paralel veya altı.', '2-1-1', 4, '5-8', 120, array['Dirseklerin düşmesi','Topukların kalkması'], array['Dirsekleri yüksek tut','Kor sıkı'], array['Goblet squat'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Front%20Squat%20exercise%20proper%20form', null, 10, 320),
  ('Bulgar Split Squat', 'Bulgarian Split Squat', 'Bacak', 'front', 'Çömelme', 'compound', 'intermediate', 'dumbbell', 'both', true, true, array['Quadriceps','Kalça'], array['Hamstring'], array['Kor','Ayak bileği'], '{}', '{}', array['Hipertrofi','Denge'], 'Arka ayak yükseltilmiş tek bacak çömelme; denge ve bacak gücü.', 'Arka ayak bench''te, ön bacakla çömel.', array['Arka ayağı bench''e koy.','Ön ayak öne adımla.','Ön dizden çömel.','Ön topuktan it.'], 'İnişte al.', 'Arka diz yere yakın.', null, 3, 'her bacak 8-12', 75, array['Ön dizin içe düşmesi','Çok kısa adım'], array['Ön topuğa yüklen','Gövde dik'], array['Split squat (yerde)'], array['Ağırlık artışı'], 'Diz valgus riski olanlar için glute medius aktivasyonuyla birlikte önerilir.', 'https://www.youtube.com/results?search_query=Bulgarian%20Split%20Squat%20exercise%20proper%20form', null, 8, 300),
  ('Leg Extension', 'Leg Extension', 'Bacak', 'front', 'İzolasyon', 'isolation', 'beginner', 'machine', 'gym', false, true, array['Quadriceps'], '{}', '{}', '{}', array['Diz stabilitesi'], array['Hipertrofi','Rehabilitasyon'], 'Quadriceps''i izole eden makine hareketi.', 'Dizden bacağı düzelt, tepede sık.', array['Makineye otur, ayak bileği pedin altında.','Bacağı düzelt.','Tepede 1 sn sık.','Kontrollü indir.'], 'Uzatışta ver.', '90°''den tam uzanışa.', null, 3, '12-15', 60, array['Momentumla savurmak'], array['Tepede sık','Yavaş indir'], array['Hafif ağırlık'], array['Tek bacak'], null, 'https://www.youtube.com/results?search_query=Leg%20Extension%20exercise%20proper%20form', null, 5, 220),
  ('Leg Curl', 'Lying Leg Curl', 'Bacak', 'back', 'İzolasyon', 'isolation', 'beginner', 'machine', 'gym', false, true, array['Hamstring'], array['Baldır'], '{}', '{}', '{}', array['Hipertrofi'], 'Hamstring izolasyon makinesi.', 'Topukları kalçaya doğru kıvır.', array['Yüzüstü uzan, ped topuk üstünde.','Topukları kalçaya çek.','Kısa dur.','Kontrollü aç.'], 'Kıvırışta ver.', 'Tam uzanıştan tam kıvırmaya.', null, 3, '10-15', 60, array['Kalça kaldırmak'], array['Kalçayı pedde tut','Yavaş'], array['Hafif ağırlık'], array['Tek bacak leg curl'], null, 'https://www.youtube.com/results?search_query=Lying%20Leg%20Curl%20exercise%20proper%20form', null, 5, 220),
  ('Yürüyen Lunge', 'Walking Lunge', 'Bacak', 'front', 'Çömelme', 'functional', 'beginner', 'dumbbell', 'both', true, true, array['Quadriceps','Kalça'], array['Hamstring','Baldır'], array['Kor'], '{}', '{}', array['Fonksiyonel','Hipertrofi'], 'İleri adımlarla dinamik tek bacak çalışması.', 'Öne adımla, arka diz yere yaklaşsın, dönüşümlü ilerle.', array['Ayakta dik dur.','Öne uzun adım at.','Her iki diz 90°.','Öne it, diğer bacakla devam.'], 'İnişte al.', 'Arka diz yere yakın.', null, 3, 'her bacak 10', 60, array['Kısa adım (diz öne kaçar)','Gövde öne düşmesi'], array['Uzun adım','Dik gövde'], array['Sabit lunge'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Walking%20Lunge%20exercise%20proper%20form', null, 8, 260),
  ('Cable Kickback', 'Cable Glute Kickback', 'Kalça', 'back', 'İzolasyon', 'isolation', 'beginner', 'cable', 'gym', false, true, array['Gluteus maximus'], array['Hamstring'], '{}', '{}', '{}', array['Hipertrofi','Aktivasyon'], 'Kalça kasını izole eden geriye tekme.', 'Ayak bileği manşetiyle bacağı geriye it.', array['Alçak makaraya ayak bileği manşeti tak.','Hafif öne eğil.','Bacağı geriye it.','Kalçayı sık, kontrollü geri getir.'], 'İtişte ver.', 'Öne uzanıştan tam ekstansiyona.', null, 3, '12-15', 45, array['Beli aşırı çukurlaştırmak'], array['Kalçayı sık','Kor sıkı'], array['Band kickback'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Cable%20Glute%20Kickback%20exercise%20proper%20form', null, 4, 200),
  ('Sumo Deadlift', 'Sumo Deadlift', 'Kalça', 'back', 'Kalça menteşesi', 'compound', 'advanced', 'barbell', 'gym', false, true, array['Gluteus maximus','Adduktorlar'], array['Hamstring','Sırt'], array['Kor'], '{}', '{}', array['Kuvvet'], 'Geniş duruşlu deadlift; kalça ve iç bacak vurgusu.', 'Ayaklar geniş, eller içeride, sırt düz, kalçadan kaldır.', array['Ayaklar geniş, parmak uçları dışa.','Barı içeriden kavra.','Göğsü kaldır, sırt düz.','Topuktan iterek kalk.'], 'Kaldırış öncesi nefes tut (bracing).', 'Yerden tam ekstansiyona.', null, 4, '3-6', 150, array['Bel yuvarlanması','Barın gövdeden uzak kalması'], array['Barı gövdeye yakın tut','Kalçayı önden geçir'], array['Trap bar deadlift'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Sumo%20Deadlift%20exercise%20proper%20form', null, 11, 340),
  ('Asılı Bacak Kaldırma', 'Hanging Leg Raise', 'Karın', 'front', 'Fleksiyon', 'core', 'advanced', 'pullup_bar', 'both', true, true, array['Alt Karın'], array['Kalça fleksörleri'], array['Kavrama'], '{}', '{}', array['Kor kuvveti'], 'Bara asılı bacak kaldırma; alt karın için etkili.', 'Bara asıl, bacakları kontrollü yukarı kaldır.', array['Bara asıl, omuzları aktive et.','Bacakları düz/bükük kaldır.','Kalçayı hafif kıvır.','Kontrollü indir.'], 'Kaldırışta ver.', 'Sarkıştan yatay/üstüne.', null, 3, '8-15', 60, array['Sallanmak','Sadece kalça fleksörü kullanmak'], array['Kalçayı kıvır','Yavaş'], array['Diz çekme','Yatarak bacak kaldırma'], array['Toes-to-bar'], null, 'https://www.youtube.com/results?search_query=Hanging%20Leg%20Raise%20exercise%20proper%20form', null, 6, 220),
  ('Kablo Crunch', 'Cable Crunch', 'Karın', 'front', 'Fleksiyon', 'core', 'beginner', 'cable', 'gym', false, true, array['Rektus abdominis'], '{}', '{}', '{}', '{}', array['Hipertrofi','Kor kuvveti'], 'Ağırlıklı karın fleksiyonu.', 'Diz üstü, halatı tutup gövdeyi karınla aşağı kıvır.', array['Yüksek makara halatını başın yanında tut.','Diz çök.','Karınla gövdeyi aşağı kıvır.','Kontrollü geri.'], 'Kıvırışta ver.', 'Dik gövdeden tam fleksiyona.', null, 3, '12-15', 60, array['Kalçadan bükmek','Kolla çekmek'], array['Karınla kıvır','Kalça sabit'], array['Crunch'], array['Ağırlık artışı'], null, 'https://www.youtube.com/results?search_query=Cable%20Crunch%20exercise%20proper%20form', null, 5, 200),
  ('Rus Twist', 'Russian Twist', 'Karın', 'front', 'Rotasyon', 'core', 'beginner', 'bodyweight', 'both', true, true, array['Obliqler'], array['Rektus abdominis'], '{}', '{}', '{}', array['Kor kuvveti','Rotasyon'], 'Oturarak gövde rotasyonuyla yan karın çalışması.', 'Gövde geride, elleri iki yana dönüşümlü götür.', array['Otur, dizler bükük, gövde geride.','Elleri birleştir.','Gövdeyi sağa-sola çevir.','Kontrollü devam et.'], 'Ritmik nefes.', 'Tam sağ-sol rotasyon.', null, 3, 'her yön 12', 45, array['Sadece kolu döndürmek','Beli yuvarlamak'], array['Gövdeyi çevir','Kor sıkı'], array['Ayaklar yerde'], array['Ağırlık/plaka ile'], null, 'https://www.youtube.com/results?search_query=Russian%20Twist%20exercise%20proper%20form', null, 5, 200),
  ('Karın Tekerleği', 'Ab Wheel Rollout', 'Karın', 'front', 'Anti-ekstansiyon', 'core', 'advanced', 'band', 'both', true, true, array['Rektus abdominis'], array['Obliqler','Sırt'], array['Omuz'], '{}', '{}', array['Kor kuvveti'], 'Tekerlekle öne açılıp kor''u anti-ekstansiyonda çalıştırma.', 'Diz üstü, tekerleği öne yuvarla, bel çökmesin.', array['Diz üstü, tekerleği tut.','Kor sıkı, öne yuvarla.','Bel nötr kalsın.','Karınla geri çek.'], 'Açılışta al, dönüşte ver.', 'Kontrol edebildiğin kadar.', null, 3, '6-10', 75, array['Belin çökmesi','Çok ileri açılmak'], array['Kalçayı hafif kıvır','Kısa mesafeyle başla'], array['Duvara doğru rollout'], array['Ayakta rollout'], null, 'https://www.youtube.com/results?search_query=Ab%20Wheel%20Rollout%20exercise%20proper%20form', null, 6, 220),
  ('Hollow Hold', 'Hollow Body Hold', 'Karın', 'front', 'İzometrik', 'stabilization', 'intermediate', 'bodyweight', 'both', true, true, array['Rektus abdominis'], array['Kalça fleksörleri'], '{}', '{}', '{}', array['Kor stabilitesi'], 'İzometrik kor duruşu; jimnastik temeli.', 'Sırtüstü, bel yere yapışık, kol-bacak havada.', array['Sırtüstü uzan.','Beli yere bastır.','Kol ve bacakları kaldır.','Pozisyonu koru.'], 'Sabit nefes.', 'İzometrik.', null, 3, null, 45, array['Belin yerden kalkması'], array['Beli yere bastır','Süreyi artır'], array['Dizleri bük'], array['Kollar baş üstünde'], null, 'https://www.youtube.com/results?search_query=Hollow%20Body%20Hold%20exercise%20proper%20form', null, 4, 30),
  ('İp Atlama', 'Jump Rope', 'Kardiyo', 'front', 'Sıçrama', 'cardio', 'beginner', 'bodyweight', 'both', true, true, array['Baldır','Kardiyovasküler'], array['Omuz','Kor'], '{}', '{}', '{}', array['Kondisyon','Yağ yakma'], 'Yüksek kalori yakan, koordinasyon geliştiren kardiyo.', 'Bilekten çevir, hafif zıpla, dik dur.', array['İpi arkada tut.','Bilekten çevir.','Parmak ucuyla hafif zıpla.','Ritmi koru.'], 'Ritmik ve düzenli.', null, null, 4, '60 sn', 45, array['Çok yüksek zıplamak','Kolla çevirmek'], array['Bilekten çevir','Kısa zıpla'], array['İpsiz taklit'], array['Çift tur (double under)'], null, 'https://www.youtube.com/results?search_query=Jump%20Rope%20exercise%20proper%20form', null, 14, 60),
  ('Yüksek Diz Koşu', 'High Knees', 'Kardiyo', 'front', 'Koşu', 'cardio', 'beginner', 'bodyweight', 'home', true, false, array['Kalça fleksörleri','Kardiyovasküler'], array['Baldır','Kor'], '{}', '{}', '{}', array['Kondisyon','Isınma'], 'Yerinde hızlı diz çekme; kalp atışını yükseltir.', 'Dizleri kalça hizasına hızlı çek.', array['Ayakta dik dur.','Dizleri sırayla kalça hizasına çek.','Kolları eşlik ettir.','Tempoyu koru.'], 'Ritmik.', null, null, 3, '40 sn', 30, array['Öne eğilmek'], array['Dik dur','Kor sıkı'], array['Yerinde yürüyüş'], array['Süre artışı'], null, 'https://www.youtube.com/results?search_query=High%20Knees%20exercise%20proper%20form', null, 10, 40),
  ('Kürek Çekme', 'Rowing Machine', 'Kardiyo', 'back', 'Çekiş', 'cardio', 'beginner', 'machine', 'gym', false, true, array['Kardiyovasküler','Sırt'], array['Bacak','Kol'], '{}', '{}', '{}', array['Kondisyon','Yağ yakma'], 'Tüm vücut düşük etkili kardiyo.', 'Bacak-gövde-kol sırasıyla it-çek.', array['Ayakları sabitle, tutmayı kavra.','Bacaktan it.','Gövdeyi hafif geri yasla.','Kolları göbeğe çek, ters sırayla dön.'], 'Çekişte ver.', null, null, 3, '5 dk', 60, array['Sadece kolla çekmek','Belden çekmek'], array['Bacak önce','Akıcı ritim'], array['Düşük direnç'], array['Interval'], null, 'https://www.youtube.com/results?search_query=Rowing%20Machine%20exercise%20proper%20form', null, 12, 300),
  ('Kutu Sıçraması', 'Box Jump', 'Bacak', 'front', 'Sıçrama', 'plyometric', 'intermediate', 'bodyweight', 'both', true, true, array['Quadriceps','Kalça'], array['Baldır'], array['Kor'], '{}', '{}', array['Patlayıcı güç','Atletizm'], 'Patlayıcı alt vücut gücü için kutuya sıçrama.', 'İki ayakla patla, kutuya yumuşak in.', array['Kutunun önünde dur.','Hafif çömel, kolları geri al.','Patlayarak sıçra.','Kutuya yumuşak, bükük dizle in.'], 'Sıçrayışta ver.', null, null, 4, '5', 90, array['Sert iniş','Çok yüksek kutu'], array['Yumuşak in','Kontrollü'], array['Step-up'], array['Kutu yüksekliği'], null, 'https://www.youtube.com/results?search_query=Box%20Jump%20exercise%20proper%20form', null, 8, 200),
  ('Skater Sıçrama', 'Skater Jumps', 'Bacak', 'front', 'Sıçrama', 'plyometric', 'intermediate', 'bodyweight', 'home', true, false, array['Gluteus medius','Quadriceps'], array['Baldır'], array['Ayak bileği','Kor'], '{}', '{}', array['Lateral güç','Denge'], 'Yanal sıçramalarla kalça ve denge çalışması.', 'Yana sıçra, tek ayağa in, dengeyi koru.', array['Tek ayak üstünde dur.','Yana patla.','Diğer ayağa in.','Dengeyi koruyarak devam et.'], 'Ritmik.', null, null, 3, 'her yön 10', 60, array['Dizin içe düşmesi','Kontrolsüz iniş'], array['Yumuşak in','Dizi hizada tut'], array['Yana adım'], array['Mesafe artışı'], null, 'https://www.youtube.com/results?search_query=Skater%20Jumps%20exercise%20proper%20form', null, 8, 200),
  ('Tek Bacak RDL', 'Single-Leg Romanian Deadlift', 'Kalça', 'back', 'Kalça menteşesi', 'balance', 'intermediate', 'dumbbell', 'both', true, true, array['Hamstring','Gluteus maximus'], array['Sırt'], array['Gluteus medius','Ayak bileği','Kor'], '{}', '{}', array['Denge','Arka zincir'], 'Tek bacak kalça menteşesi; denge ve hamstring gücü.', 'Tek bacakta kalçadan öne menteşele, sırt düz.', array['Tek bacakta dur, hafif diz bükük.','Kalçadan öne eğil.','Arka bacak geriye uzanır.','Kalçayı sıkarak doğrul.'], 'İnişte al.', 'Gövde yere paralel yaklaşana kadar.', null, 3, 'her bacak 8-10', 60, array['Belin yuvarlanması','Kalçanın açılması (rotasyon)'], array['Kalçayı kare tut','Yavaş kontrol'], array['Destekli SL-RDL'], array['Ağırlık artışı'], 'Kalça asimetrisi ve denge zayıflığında çok etkili.', 'https://www.youtube.com/results?search_query=Single-Leg%20Romanian%20Deadlift%20exercise%20proper%20form', null, 6, 240),
  ('Ayı Yürüyüşü', 'Bear Crawl', 'Karın', 'front', 'Fonksiyonel', 'stabilization', 'beginner', 'bodyweight', 'home', true, false, array['Kor'], array['Omuz','Quadriceps'], array['Tüm gövde'], '{}', '{}', array['Stabilizasyon','Koordinasyon'], 'Dört ayak üstünde karşıt kol-bacak ilerleme.', 'Dizler yerden hafif yukarı, sırt düz, karşıt kol-bacak ilerlet.', array['Dört ayak pozisyonu, dizler 2 cm yukarı.','Karşıt kol-bacak öne.','Kalça sabit, sırt düz.','İlerlemeye devam et.'], 'Sabit nefes.', null, null, 3, '20 adım', 45, array['Kalçanın sallanması'], array['Kalçayı sabit tut','Yavaş'], array['Yerinde bear hold'], array['Geri/yana crawl'], null, 'https://www.youtube.com/results?search_query=Bear%20Crawl%20exercise%20proper%20form', null, 6, 40),
  ('Dünyanın En İyi Esnemesi', 'World''s Greatest Stretch', 'Kalça', 'front', 'Mobilite', 'mobility', 'beginner', 'bodyweight', 'both', true, true, array['Kalça fleksörleri','Torakal omurga'], array['Hamstring'], '{}', array['Kalça','Torakal rotasyon'], '{}', array['Isınma','Mobilite'], 'Antrenman öncesi tüm vücut dinamik esneme.', 'Lunge pozisyonda dirseği yere değdir, gövdeyi aç.', array['Öne uzun lunge adımı at.','Ön ayak yanına dirseği götür.','Aynı kolu tavana aç (rotasyon).','Yer değiştir.'], 'Açılışta derin nefes.', null, null, 2, 'her yön 5', 20, array['Aceleci geçmek'], array['Yavaş ve kontrollü','Rotasyonu hisset'], array['Sadece lunge'], array['Daha derin açı'], null, 'https://www.youtube.com/results?search_query=World''s%20Greatest%20Stretch%20exercise%20proper%20form', null, 3, 60),
  ('90/90 Kalça Geçişi', '90/90 Hip Switch', 'Kalça', 'front', 'Mobilite', 'mobility', 'beginner', 'bodyweight', 'home', true, false, array['Kalça'], '{}', '{}', array['Kalça iç/dış rotasyon'], '{}', array['Mobilite'], 'Kalça iç ve dış rotasyon aralığını geliştiren oturma geçişi.', 'Oturarak dizleri 90/90''da yana çevir.', array['Yere otur, dizler 90/90.','Gövdeyi dik tut.','Dizleri diğer yana çevir.','Ritmik geçiş yap.'], 'Ritmik.', null, null, 2, 'her yön 8', 20, array['Belin yuvarlanması'], array['Gövde dik','Yavaş'], array['Kısmi açı'], array['Öne uzanma ekle'], null, 'https://www.youtube.com/results?search_query=90%2F90%20Hip%20Switch%20exercise%20proper%20form', null, 2, 60),
  ('Kol Çevirme', 'Arm Circles', 'Omuz', 'front', 'Mobilite', 'warmup', 'beginner', 'bodyweight', 'home', true, false, array['Omuz'], '{}', '{}', array['Omuz'], '{}', array['Isınma'], 'Omuz eklemini ısıtan dinamik çevirme.', 'Kolları küçükten büyüğe daireler çiz.', array['Kolları yana aç.','Küçük daireler çiz.','Giderek büyüt.','Yön değiştir.'], 'Serbest.', null, null, 1, 'her yön 15', 15, array['Omuz silkme'], array['Kontrollü','Boynu gevşek tut'], '{}', array['Band ile'], null, 'https://www.youtube.com/results?search_query=Arm%20Circles%20exercise%20proper%20form', null, 2, 40),
  ('Solucan Yürüyüşü', 'Inchworm', 'Karın', 'front', 'Fonksiyonel', 'warmup', 'beginner', 'bodyweight', 'home', true, false, array['Kor','Hamstring'], array['Omuz'], '{}', array['Arka zincir'], '{}', array['Isınma','Mobilite'], 'Ellerle öne yürüyüp plank''a geçen dinamik ısınma.', 'Öne eğil, ellerle plank''a yürü, geri dön.', array['Ayakta öne eğil, elleri yere koy.','Elle plank''a yürü.','Bir şınav (opsiyonel).','Ayaklara doğru geri yürü.'], 'Ritmik.', null, null, 2, '6', 20, array['Belin çökmesi'], array['Kor sıkı','Yavaş'], array['Diz bükük'], array['Şınav ekle'], null, 'https://www.youtube.com/results?search_query=Inchworm%20exercise%20proper%20form', null, 4, 50),
  ('Kelebek Esnemesi', 'Butterfly Stretch', 'Kalça', 'front', 'Esneme', 'stretch', 'beginner', 'bodyweight', 'home', true, false, array['Adduktorlar'], array['Kalça'], '{}', array['Kalça iç'], '{}', array['Esneklik','Soğuma'], 'İç bacak esnekliği için oturma esnemesi.', 'Ayak tabanlarını birleştir, dizleri nazikçe indir.', array['Otur, ayak tabanlarını birleştir.','Topukları gövdeye çek.','Dizleri nazikçe indir.','30 sn koru.'], 'Derin ve yavaş.', null, null, 2, null, 15, array['Zıplayarak zorlamak'], array['Nazik bas','Sırtı dik tut'], '{}', array['Öne uzan'], null, 'https://www.youtube.com/results?search_query=Butterfly%20Stretch%20exercise%20proper%20form', null, 1, 30),
  ('Çocuk Pozu Esnemesi', 'Child''s Pose Stretch', 'Sırt', 'back', 'Esneme', 'cooldown', 'beginner', 'bodyweight', 'home', true, false, array['Bel','Sırt'], array['Kalça'], '{}', array['Omurga'], '{}', array['Soğuma','Gevşeme'], 'Sırt ve kalçayı gevşeten dinlendirici poz.', 'Diz üstü otur, kolları öne uzat, alnı yere koy.', array['Diz üstü otur.','Kalçayı topuklara götür.','Kolları öne uzat.','Nefesle gevşe.'], 'Derin karın nefesi.', null, null, 1, null, 0, array['Zorlamak'], array['Nefese odaklan','Omuzları gevşet'], '{}', array['Yana uzan'], null, 'https://www.youtube.com/results?search_query=Child''s%20Pose%20Stretch%20exercise%20proper%20form', null, 1, 60),
  ('Kobra Esnemesi', 'Cobra Stretch', 'Karın', 'front', 'Esneme', 'cooldown', 'beginner', 'bodyweight', 'home', true, false, array['Karın ön duvarı'], array['Bel'], '{}', array['Omurga ekstansiyonu'], '{}', array['Soğuma','Esneklik'], 'Karın ön zincirini açan nazik geriye esneme.', 'Yüzüstü yat, elle gövdeyi nazikçe kaldır.', array['Yüzüstü uzan, eller omuz altında.','Kalçayı yerde tut.','Gövdeyi nazikçe kaldır.','Boynu uzat, koru.'], 'Yavaş nefes.', null, null, 2, null, 15, array['Boynu geriye kırmak'], array['Kalçayı yerde tut','Nazik'], array['Dirsek üstü'], array['Daha yüksek'], null, 'https://www.youtube.com/results?search_query=Cobra%20Stretch%20exercise%20proper%20form', null, 1, 30)
on conflict (name) do update set
  english_name = excluded.english_name,
  muscle_group = excluded.muscle_group,
  body_region = excluded.body_region,
  movement_type = excluded.movement_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  equipment = excluded.equipment,
  environment = excluded.environment,
  is_home = excluded.is_home,
  is_gym = excluded.is_gym,
  primary_muscles = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  stabilizer_muscles = excluded.stabilizer_muscles,
  mobility_focus = excluded.mobility_focus,
  rehabilitation_focus = excluded.rehabilitation_focus,
  exercise_goal = excluded.exercise_goal,
  description = excluded.description,
  correct_form = excluded.correct_form,
  instructions = excluded.instructions,
  breathing = excluded.breathing,
  range_of_motion = excluded.range_of_motion,
  tempo = excluded.tempo,
  rec_sets = excluded.rec_sets,
  rec_reps = excluded.rec_reps,
  rec_rest_sec = excluded.rec_rest_sec,
  common_mistakes = excluded.common_mistakes,
  tips = excluded.tips,
  regressions = excluded.regressions,
  progressions = excluded.progressions,
  ai_notes = excluded.ai_notes,
  video_url = excluded.video_url,
  gif_url = excluded.gif_url,
  calories = excluded.calories,
  average_duration_sec = excluded.average_duration_sec;

-- Yeni satırlar için slug üret (mevcut null olanlar).
update public.exercises
set slug = trim(both '-' from regexp_replace(lower(unaccent(name)), '[^a-z0-9]+', '-', 'g'))
where slug is null or slug = '';
