-- ============================================================================
-- Viva AI Coach — Kas Kütüphanesi Seed (Sprint 3, Anatomy Explorer)
-- 14 major kas; Türkçe anatomi (origo/insertio/innervasyon), fonksiyonlar,
-- sık sakatlıklar, rehabilitasyon notları. svg_region_id = slug.
-- İdempotent (upsert). schema.sql sonrası çalıştırılır.
-- ============================================================================

insert into public.muscles
  (slug, name_tr, latin_name, muscle_group, region, svg_region_id, sort_order,
   overview, functions, origin, insertion, innervation, common_injuries, rehab_notes)
values
('gogus', 'Göğüs', 'Pectoralis Major', 'Göğüs', 'front', 'gogus', 10,
 'Göğüs ön duvarının büyük, yelpaze biçimli kası. İtme hareketlerinin ana gücü.',
 array['Kolun öne getirilmesi (fleksiyon)','Kolun gövdeye yaklaştırılması (adduksiyon)','Kolun içe rotasyonu'],
 'Klavikula iç yarısı, sternum ve üst kaburga kıkırdakları',
 'Humerus (üst kol kemiği) büyük tüberkül krestası',
 'Medial ve lateral pektoral sinirler',
 array['Pektoral yırtık (ağır bench press)','Omuz ön kapsül zorlanması'],
 'Ağrı geçtikten sonra hafif bant/şınav ile kademeli yükleme; tam açıklığı zorlama.'),

('omuz', 'Omuz', 'Deltoid', 'Omuz', 'front', 'omuz', 20,
 'Omuzu saran üç başlı (ön-yan-arka) kas; kolu her yönde kaldırır.',
 array['Kolun yana kaldırılması (abduksiyon)','Ön baş: fleksiyon','Arka baş: ekstansiyon'],
 'Klavikula dış ucu, akromion ve spina skapula',
 'Humerus deltoid tüberositesi',
 'Aksiller sinir',
 array['Sıkışma sendromu (impingement)','Rotator manşet zorlanması'],
 'Ağrısız açıklıkta band ile dış rotasyon; yük öncesi skapular kontrol çalış.'),

('biceps', 'Biceps', 'Biceps Brachii', 'Kol', 'front', 'biceps', 30,
 'Üst kolun önündeki iki başlı kas; dirsek bükme ve ön kol döndürme.',
 array['Dirsek fleksiyonu','Ön kol supinasyonu (avuç yukarı)','Omuz fleksiyonuna yardım'],
 'Skapula (korakoid çıkıntı ve supraglenoid tüberkül)',
 'Radius tüberositesi',
 'Muskülokutanöz sinir',
 array['Biceps tendon tendiniti','Uzun baş tendon yırtığı'],
 'İzometrik curl ile başla; ağrı azaldıkça eksantrik (yavaş iniş) ekle.'),

('triceps', 'Triceps', 'Triceps Brachii', 'Kol', 'back', 'triceps', 40,
 'Üst kolun arkasındaki üç başlı kas; dirseği düzleştiren ana kas.',
 array['Dirsek ekstansiyonu','Uzun baş: omuz ekstansiyonu'],
 'Skapula (infraglenoid) ve humerus arka yüzü',
 'Ulna olekranon çıkıntısı',
 'Radial sinir',
 array['Triceps tendiniti','Dirsek aşırı yüklenmesi'],
 'Pushdown''da dirseği sabit tut; ağrıda hafif band ekstansiyonu.'),

('on-kol', 'Ön Kol', 'Fleksör/Ekstansör Grubu', 'Kol', 'front', 'on-kol', 50,
 'Bileği ve parmakları hareket ettiren, kavrama gücünü belirleyen kas grubu.',
 array['Bilek fleksiyon/ekstansiyonu','Parmak hareketleri','Kavrama (grip)'],
 'Humerus medial ve lateral epikondili',
 'El bileği ve parmak kemikleri',
 'Median, ulnar ve radial sinirler',
 array['Tenisçi dirseği (lateral epikondilit)','Golfçü dirseği'],
 'Kavrama ağrısında eksantrik bilek çalışması ve dinlenme etkilidir.'),

('karin', 'Karın', 'Rectus Abdominis', 'Karın', 'front', 'karin', 60,
 'Karnın ön duvarındaki "six-pack" kası; gövdeyi öne büker ve stabilize eder.',
 array['Gövde fleksiyonu','Pelvis geriye eğimi','Core stabilizasyonu'],
 'Pubis kemiği (kasık)',
 '5-7. kaburga kıkırdakları ve sternum ucu',
 'Torakoabdominal sinirler (T7-T12)',
 array['Karın kası zorlanması','Fıtık (aşırı ıkınma)'],
 'Plank gibi izometrik core ile başla; ağrıda fleksiyon hareketlerini azalt.'),

('yan-karin', 'Yan Karın', 'Obliquus (Eğik Karın)', 'Karın', 'front', 'yan-karin', 70,
 'Karnın yan duvarındaki iç ve dış eğik kaslar; dönme ve yana eğilme.',
 array['Gövde rotasyonu','Yana fleksiyon','Karın içi basıncı artırma'],
 'Alt kaburgalar ve pelvis',
 'Linea alba, pubis ve iliak krest',
 'Torakoabdominal ve iliohipogastrik sinirler',
 array['Yan karın zorlanması','Interkostal ağrı'],
 'Rotasyonel hareketlerde kontrollü tempo; ani dönüşlerden kaçın.'),

('trapez', 'Trapez', 'Trapezius', 'Sırt', 'back', 'trapez', 80,
 'Boyun ve üst sırtı kaplayan büyük eşkenar kas; skapulayı hareket ettirir.',
 array['Skapula elevasyonu (omuz silkme)','Skapula geri çekme','Aşağı çekme'],
 'Kafatası tabanı, boyun ve sırt omurları (dikensi çıkıntılar)',
 'Klavikula dış ucu, akromion ve spina skapula',
 'Aksesuar sinir (CN XI)',
 array['Boyun-üst sırt gerginliği','Tetik nokta ağrısı'],
 'Masa başı gerginliğinde germe + hafif kürek çekme; postür çalışması.'),

('sirt', 'Sırt (Kanat)', 'Latissimus Dorsi', 'Sırt', 'back', 'sirt', 90,
 'Sırtın en geniş kası; çekiş hareketlerinde "kanat" görünümünü verir.',
 array['Kol adduksiyonu','Kol ekstansiyonu','Kolun içe rotasyonu'],
 'Alt sırt omurları, torakolumbar fasya ve iliak krest',
 'Humerus interтüberküler oluk',
 'Torakodorsal sinir',
 array['Lat zorlanması (ağır deadlift/pull-up)','Omuz arka ağrısı'],
 'Barfiks/lat pulldown''da tam açıklık ve kontrollü iniş; ağrıda band ile başla.'),

('bel', 'Bel', 'Erector Spinae', 'Sırt', 'back', 'bel', 100,
 'Omurga boyunca uzanan, dik durmayı sağlayan derin kas grubu.',
 array['Omurga ekstansiyonu (dik durma)','Yana eğilme','Postür stabilizasyonu'],
 'Sakrum, iliak krest ve alt omurlar',
 'Kaburgalar ve üst omurlar',
 'Spinal sinirlerin dorsal dalları',
 array['Bel kası zorlanması','Disk hassasiyeti'],
 'Nötr omurga ile "bird-dog" ve hip hinge; ağırlığı çok kademeli artır.'),

('kalca', 'Kalça', 'Gluteus Maximus', 'Kalça', 'back', 'kalca', 110,
 'Vücudun en güçlü kaslarından; kalça ekstansiyonu ve güç üretiminin merkezi.',
 array['Kalça ekstansiyonu','Dış rotasyon','Pelvis stabilizasyonu'],
 'İlium arka yüzü, sakrum ve koksiks',
 'Femur gluteal tüberosite ve iliotibial bant',
 'İnferior gluteal sinir',
 array['Gluteal amnezi (zayıf aktivasyon)','Piriformis sendromu'],
 'Glute bridge ve hip thrust ile aktivasyon; zirvede bilinçli sıkma.'),

('on-bacak', 'Ön Bacak', 'Quadriceps', 'Bacak', 'front', 'on-bacak', 120,
 'Uyluk önündeki dört başlı kas; dizi düzleştirir, squat ve koşunun motoru.',
 array['Diz ekstansiyonu','Rectus femoris: kalça fleksiyonu'],
 'Femur ve ilium (rectus femoris)',
 'Patella üzerinden tibia tüberositesi',
 'Femoral sinir',
 array['Patellar tendinit (zıplayıcı dizi)','Quad zorlanması'],
 'Ağrısız açıklıkta squat; patellar tendinitte eksantrik yavaş iniş etkili.'),

('arka-bacak', 'Arka Bacak', 'Hamstrings', 'Bacak', 'back', 'arka-bacak', 130,
 'Uyluk arkasındaki üç kaslı grup; dizi büker, kalçayı ekstansiyona getirir.',
 array['Diz fleksiyonu','Kalça ekstansiyonu','Koşuda frenleme'],
 'İskium tüberositesi (oturma kemiği)',
 'Tibia ve fibula üst uçları',
 'Siyatik sinir',
 array['Hamstring yırtığı (sprint)','Oturma kemiği tendinopatisi'],
 'Isınma şart; Romanian deadlift ve Nordic curl ile kademeli güçlendir.'),

('baldir', 'Baldır', 'Gastrocnemius / Soleus', 'Bacak', 'back', 'baldir', 140,
 'Alt bacağın arkasındaki kas; ayak parmak ucuna kalkma ve itiş hareketi.',
 array['Ayak bileği plantar fleksiyonu (parmak ucuna kalkma)','Koşu/zıplamada itiş'],
 'Femur alt ucu (gastrocnemius) ve tibia/fibula (soleus)',
 'Aşil tendonu üzerinden topuk kemiği (kalkaneus)',
 'Tibial sinir',
 array['Aşil tendiniti','Baldır krampı/yırtığı'],
 'Aşil sorununda eksantrik topuk düşürme egzersizi altın standarttır.')

on conflict (slug) do update set
  name_tr=excluded.name_tr, latin_name=excluded.latin_name, muscle_group=excluded.muscle_group,
  region=excluded.region, svg_region_id=excluded.svg_region_id, sort_order=excluded.sort_order,
  overview=excluded.overview, functions=excluded.functions, origin=excluded.origin,
  insertion=excluded.insertion, innervation=excluded.innervation,
  common_injuries=excluded.common_injuries, rehab_notes=excluded.rehab_notes;
