-- ===========================================================================
-- Migration 0050 — Workout Engine temeli + egzersiz isim standardizasyonu
--
-- İKİ İŞ YAPAR:
--   A) Workout Engine için eksik sütunlar (RIR/RPE/hedef tekrar/dinlenme)
--   B) `english_name` standardizasyonu + `aliases` + `video_slug`
--
-- KRİTİK: `exercises.name` sütununa DOKUNULMAZ.
--   `workout_sets.exercise_name` ve `personal_records.exercise_name` bu ismin
--   kopyasını tutuyor; PR tablosunun benzersizlik kısıtı da (unique(user_id,
--   exercise_name)) ona bağlı. `name` değişseydi tüm geçmiş antrenman ve
--   rekor kayıtları kopardı. Bu yüzden `name` iç anahtar olarak kalıyor,
--   kullanıcıya gösterilen isim `english_name` üzerinden çözülüyor.
--
-- Additive + idempotent. İki kez çalıştırılabilir.
-- ===========================================================================

-- --- YEDEK ---------------------------------------------------------------
-- İsim güncellemelerinden ÖNCE mevcut durumu sakla. Geri dönüş:
--   update public.exercises e set english_name = b.english_name
--     from public.exercises_name_backup b where b.id = e.id;
create table if not exists public.exercises_name_backup (
  id           uuid,
  name         text,
  english_name text,
  backed_up_at timestamptz not null default now()
);

-- Yedek yalnızca BOŞSA doldurulur.
--   · İlk çalıştırma  → değişiklikten önceki hali kaydedilir (istenen)
--   · Tekrar çalıştırma → ilk yedek KORUNUR, üzerine yazılmaz
-- `create table if not exists ... as select` bunu yapamıyordu: tablo herhangi
-- bir sebeple önceden oluşmuşsa (ör. veri yüklenmeden önce çalıştırıldıysa)
-- yedek sonsuza kadar boş kalıyor ve UPDATE'ler yine de işliyordu.
insert into public.exercises_name_backup (id, name, english_name)
select id, name, english_name from public.exercises
where not exists (select 1 from public.exercises_name_backup);

-- --- A) WORKOUT ENGINE SÜTUNLARI ------------------------------------------
-- Şu ana kadar set satırı yalnızca "kaç tekrar, kaç kilo" tutuyordu. Motor
-- için hedef/gerçekleşen ayrımı ve efor ölçüsü gerekiyor.
alter table public.workout_sets
  add column if not exists target_reps int,               -- planlanan tekrar
  add column if not exists rir         int,               -- Reps In Reserve (0-5)
  add column if not exists rpe         numeric(3,1),      -- Rate of Perceived Exertion (1-10)
  add column if not exists rest_sec    int,               -- bu setten sonra dinlenilen süre
  add column if not exists notes       text;

-- Aralık koruması: bozuk istemci verisi ilerleme hesabını yanıltmasın.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'workout_sets_rir_range') then
    alter table public.workout_sets add constraint workout_sets_rir_range
      check (rir is null or (rir >= 0 and rir <= 10));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'workout_sets_rpe_range') then
    alter table public.workout_sets add constraint workout_sets_rpe_range
      check (rpe is null or (rpe >= 1 and rpe <= 10));
  end if;
end $$;

-- --- B) İSİM STANDARDİZASYONU ---------------------------------------------
alter table public.exercises
  add column if not exists aliases    text[] not null default '{}',
  add column if not exists video_slug text;

-- english_name standardizasyonu (üretilmiştir:
-- scripts/standardize-exercise-names.py --sql)
-- `name` sütununa DOKUNULMAZ: workout_sets.exercise_name ve
-- personal_records.exercise_name ona bağlı.
update public.exercises set english_name = 'Push-Up' where name = 'Şınav';
update public.exercises set english_name = 'Barbell Bench Press' where name = 'Bench Press';
update public.exercises set english_name = 'Plank' where name = 'Plank';
update public.exercises set english_name = 'Sit-Up' where name = 'Mekik';
update public.exercises set english_name = 'Pull-Up' where name = 'Barfiks';
update public.exercises set english_name = 'Conventional Deadlift' where name = 'Deadlift';
update public.exercises set english_name = 'Lat Pulldown' where name = 'Lat Pulldown';
update public.exercises set english_name = 'Back Squat' where name = 'Squat';
update public.exercises set english_name = 'Dumbbell Shoulder Press' where name = 'Omuz Press';
update public.exercises set english_name = 'Dumbbell Biceps Curl' where name = 'Biceps Curl';
update public.exercises set english_name = 'Triceps Pushdown' where name = 'Triceps Pushdown';
update public.exercises set english_name = 'Lunge' where name = 'Lunges';
update public.exercises set english_name = 'Leg Press' where name = 'Leg Press';
update public.exercises set english_name = 'Burpee' where name = 'Burpee';
update public.exercises set english_name = 'Treadmill Running' where name = 'Koşu Bandı';
update public.exercises set english_name = 'Standing Calf Raise' where name = 'Ayakta Vücut Ağırlığı Calf Raise';
update public.exercises set english_name = 'Leg Raise' where name = 'Bacak Kaldırma';
update public.exercises set english_name = 'Hanging Leg Raise' where name = 'Barfiks Barı Bacak Kaldırma';
update public.exercises set english_name = 'Pull-Up' where name = 'Barfiks Barı Barfiks';
update public.exercises set english_name = 'Bulgarian Lunge' where name = 'Bulgar Vücut Ağırlığı Lunge';
update public.exercises set english_name = 'Bulgarian Bodyweight Split Squat' where name = 'Bulgar Vücut Ağırlığı Split Squat';
update public.exercises set english_name = 'Close-Grip Pull-Up' where name = 'Dar Tutuş Barfiks Barı Barfiks';
update public.exercises set english_name = 'Close-Grip Resistance Band Triceps Pushdown' where name = 'Dar Tutuş Direnç Bandı Triceps Pushdown';
update public.exercises set english_name = 'Close-Grip Push-Up' where name = 'Dar Tutuş Vücut Ağırlığı Şınav';
update public.exercises set english_name = 'Diamond Push-Up' where name = 'Diamond Şınav';
update public.exercises set english_name = 'Resistance Band Pull-Through' where name = 'Direnç Bandı Cable Pull-Through';
update public.exercises set english_name = 'Resistance Band Woodchop' where name = 'Direnç Bandı Cable Woodchop';
update public.exercises set english_name = 'Resistance Band Cuban Press' where name = 'Direnç Bandı Cuban Press';
update public.exercises set english_name = 'Resistance Band External Rotation' where name = 'Direnç Bandı Dış Rotasyon';
update public.exercises set english_name = 'Resistance Band Straight-Arm Pulldown' where name = 'Direnç Bandı Düz Kol Pulldown';
update public.exercises set english_name = 'Resistance Band Face Pull' where name = 'Direnç Bandı Face Pull';
update public.exercises set english_name = 'Resistance Band Front Raise' where name = 'Direnç Bandı Front Raise';
update public.exercises set english_name = 'Resistance Band Glute Kickback' where name = 'Direnç Bandı Glute Kickback';
update public.exercises set english_name = 'Resistance Band Hip Abduction' where name = 'Direnç Bandı Kalça Abdüksiyon';
update public.exercises set english_name = 'Resistance Band Hip Adduction' where name = 'Direnç Bandı Kalça Addüksiyon';
update public.exercises set english_name = 'Resistance Band Tibialis Raise' where name = 'Direnç Bandı Tibialis Raise';
update public.exercises set english_name = 'Resistance Band Triceps Pushdown' where name = 'Direnç Bandı Triceps Pushdown';
update public.exercises set english_name = 'Dumbbell Bench Press' where name = 'Dumbbell Press';
update public.exercises set english_name = 'Dumbbell Row' where name = 'Dumbbell Row';
update public.exercises set english_name = 'Incline Push-Up' where name = 'Eğik Vücut Ağırlığı Şınav';
update public.exercises set english_name = 'Wide-Grip Pull-Up' where name = 'Geniş Tutuş Barfiks Barı Barfiks';
update public.exercises set english_name = 'Wide-Grip Push-Up' where name = 'Geniş Tutuş Vücut Ağırlığı Şınav';
update public.exercises set english_name = 'Glute Bridge' where name = 'Glute Bridge';
update public.exercises set english_name = 'Goblet Squat' where name = 'Goblet Squat';
update public.exercises set english_name = 'Hamstring Stretch' where name = 'Hamstring Esnetme';
update public.exercises set english_name = 'Barbell Hip Thrust' where name = 'Hip Thrust';
update public.exercises set english_name = 'Cat-Cow' where name = 'Kedi-Deve';
update public.exercises set english_name = 'Dumbbell Lateral Raise' where name = 'Lateral Raise';
update public.exercises set english_name = 'Mountain Climber' where name = 'Mountain Climber';
update public.exercises set english_name = 'Neutral-Grip Pull-Up' where name = 'Nötr Tutuş Barfiks Barı Barfiks';
update public.exercises set english_name = 'Seated Calf Raise' where name = 'Oturarak Vücut Ağırlığı Calf Raise';
update public.exercises set english_name = 'Romanian Deadlift' where name = 'Romanian Deadlift';
update public.exercises set english_name = 'Single-Leg Bodyweight Calf Raise' where name = 'Tek Bacak Vücut Ağırlığı Calf Raise';
update public.exercises set english_name = 'Single-Leg Hip Thrust' where name = 'Tek Bacak Vücut Ağırlığı Hip Thrust';
update public.exercises set english_name = 'Single-Leg Lunge' where name = 'Tek Bacak Vücut Ağırlığı Lunge';
update public.exercises set english_name = 'Single-Leg Plank' where name = 'Tek Bacak Vücut Ağırlığı Plank';
update public.exercises set english_name = 'Single-Arm Plank' where name = 'Tek Kol Vücut Ağırlığı Plank';
update public.exercises set english_name = 'Reverse Resistance Band Triceps Pushdown' where name = 'Ters Direnç Bandı Triceps Pushdown';
update public.exercises set english_name = 'Decline Push-Up' where name = 'Ters Eğik Vücut Ağırlığı Şınav';
update public.exercises set english_name = 'Decline Sit-Up' where name = 'Ters Eğik Vücut Ağırlığı Sit-Up';
update public.exercises set english_name = 'Reverse Crunch' where name = 'Ters Vücut Ağırlığı Crunch';
update public.exercises set english_name = 'Reverse Lunge' where name = 'Ters Vücut Ağırlığı Lunge';
update public.exercises set english_name = 'Leg Raise' where name = 'Vücut Ağırlığı Bacak Kaldırma';
update public.exercises set english_name = 'Crunch' where name = 'Vücut Ağırlığı Crunch';
update public.exercises set english_name = 'Hip Thrust' where name = 'Vücut Ağırlığı Hip Thrust';
update public.exercises set english_name = 'Lunge' where name = 'Vücut Ağırlığı Lunge';
update public.exercises set english_name = 'Plank' where name = 'Vücut Ağırlığı Plank';
update public.exercises set english_name = 'Bodyweight Russian Twist' where name = 'Vücut Ağırlığı Rus Twist';
update public.exercises set english_name = 'Push-Up' where name = 'Vücut Ağırlığı Şınav';
update public.exercises set english_name = 'Back Extension' where name = 'Vücut Ağırlığı Sırt Ekstansiyonu';
update public.exercises set english_name = 'Sit-Up' where name = 'Vücut Ağırlığı Sit-Up';
update public.exercises set english_name = 'Split Squat' where name = 'Vücut Ağırlığı Split Squat';
update public.exercises set english_name = 'Step-Up' where name = 'Vücut Ağırlığı Step-Up';
update public.exercises set english_name = 'Tibialis Raise' where name = 'Vücut Ağırlığı Tibialis Raise';

-- video_slug: standart isimden türetilir
update public.exercises set video_slug = 'push-up' where name = 'Şınav';
update public.exercises set video_slug = 'barbell-bench-press' where name = 'Bench Press';
update public.exercises set video_slug = 'plank' where name = 'Plank';
update public.exercises set video_slug = 'sit-up' where name = 'Mekik';
update public.exercises set video_slug = 'pull-up' where name = 'Barfiks';
update public.exercises set video_slug = 'conventional-deadlift' where name = 'Deadlift';
update public.exercises set video_slug = 'lat-pulldown' where name = 'Lat Pulldown';
update public.exercises set video_slug = 'back-squat' where name = 'Squat';
update public.exercises set video_slug = 'dumbbell-shoulder-press' where name = 'Omuz Press';
update public.exercises set video_slug = 'dumbbell-biceps-curl' where name = 'Biceps Curl';
update public.exercises set video_slug = 'triceps-pushdown' where name = 'Triceps Pushdown';
update public.exercises set video_slug = 'incline-dumbbell-press' where name = 'Eğik Dumbbell Press';
update public.exercises set video_slug = 'cable-chest-fly' where name = 'Cable Fly';
update public.exercises set video_slug = 'chest-dips' where name = 'Dips (Göğüs)';
update public.exercises set video_slug = 'bent-over-barbell-row' where name = 'Barbell Row';
update public.exercises set video_slug = 'chest-supported-row' where name = 'Göğüs Destekli Row';
update public.exercises set video_slug = 'lunge' where name = 'Lunges';
update public.exercises set video_slug = 'straight-arm-pulldown' where name = 'Düz Kol Pulldown';
update public.exercises set video_slug = 'arnold-press' where name = 'Arnold Press';
update public.exercises set video_slug = 'cable-lateral-raise' where name = 'Cable Lateral Raise';
update public.exercises set video_slug = 'cable-face-pull' where name = 'Face Pull (Omuz)';
update public.exercises set video_slug = 'hammer-curl' where name = 'Hammer Curl';
update public.exercises set video_slug = 'lying-triceps-extension' where name = 'Skullcrusher';
update public.exercises set video_slug = 'chin-up' where name = 'Barfiks (Chin-up)';
update public.exercises set video_slug = 'box-jump' where name = 'Kutu Sıçraması';
update public.exercises set video_slug = 'front-squat' where name = 'Front Squat';
update public.exercises set video_slug = 'bulgarian-split-squat' where name = 'Bulgar Split Squat';
update public.exercises set video_slug = 'leg-extension' where name = 'Leg Extension';
update public.exercises set video_slug = 'lying-leg-curl' where name = 'Leg Curl';
update public.exercises set video_slug = 'walking-lunge' where name = 'Yürüyen Lunge';
update public.exercises set video_slug = 'cable-glute-kickback' where name = 'Cable Kickback';
update public.exercises set video_slug = 'sumo-deadlift' where name = 'Sumo Deadlift';
update public.exercises set video_slug = 'skater-jumps' where name = 'Skater Sıçrama';
update public.exercises set video_slug = 'hanging-leg-raise' where name = 'Asılı Bacak Kaldırma';
update public.exercises set video_slug = 'cable-crunch' where name = 'Kablo Crunch';
update public.exercises set video_slug = 'russian-twist' where name = 'Rus Twist';
update public.exercises set video_slug = 'ab-wheel-rollout' where name = 'Karın Tekerleği';
update public.exercises set video_slug = 'hollow-body-hold' where name = 'Hollow Hold';
update public.exercises set video_slug = 'jump-rope' where name = 'İp Atlama';
update public.exercises set video_slug = 'high-knees' where name = 'Yüksek Diz Koşu';
update public.exercises set video_slug = 'rowing-machine' where name = 'Kürek Çekme';
update public.exercises set video_slug = 'single-leg-romanian-deadlift' where name = 'Tek Bacak RDL';
update public.exercises set video_slug = 'bear-crawl' where name = 'Ayı Yürüyüşü';
update public.exercises set video_slug = 'world-s-greatest-stretch' where name = 'Dünyanın En İyi Esnemesi';
update public.exercises set video_slug = '90-90-hip-switch' where name = '90/90 Kalça Geçişi';
update public.exercises set video_slug = 'arm-circles' where name = 'Kol Çevirme';
update public.exercises set video_slug = 'inchworm' where name = 'Solucan Yürüyüşü';
update public.exercises set video_slug = 'butterfly-stretch' where name = 'Kelebek Esnemesi';
update public.exercises set video_slug = 'child-s-pose-stretch' where name = 'Çocuk Pozu Esnemesi';
update public.exercises set video_slug = 'cobra-stretch' where name = 'Kobra Esnemesi';
update public.exercises set video_slug = 'leg-press' where name = 'Leg Press';
update public.exercises set video_slug = 'burpee' where name = 'Burpee';
update public.exercises set video_slug = 'treadmill-running' where name = 'Koşu Bandı';
update public.exercises set video_slug = '4-7-8-breathing' where name = '4-7-8 Nefesi';
update public.exercises set video_slug = 'a-skip' where name = 'A-Skip';
update public.exercises set video_slug = 'ab-wheel-rollout' where name = 'Ab Wheel Rollout';
update public.exercises set video_slug = 'open-book-rotation' where name = 'Açık Kitap Rotasyonu';
update public.exercises set video_slug = 'adductor-stretch' where name = 'Adductor Esnetme';
update public.exercises set video_slug = 'tree-pose' where name = 'Ağaç Pozu';
update public.exercises set video_slug = 'clap-push-up' where name = 'Alkışlı Şınav';
update public.exercises set video_slug = 'downward-dog' where name = 'Aşağı Bakan Köpek';
update public.exercises set video_slug = 'hanging-knee-raise' where name = 'Asılı Diz Çekme';
update public.exercises set video_slug = 'australian-row' where name = 'Australian Row';
update public.exercises set video_slug = 'ankle-eversion' where name = 'Ayak Bileği Eversiyon';
update public.exercises set video_slug = 'ankle-mobilization' where name = 'Ayak Bileği Mobilizasyonu';
update public.exercises set video_slug = 'foot-trigger-point-release' where name = 'Ayak Tabanı Tetik Nokta';
update public.exercises set video_slug = 'standing-barbell-biceps-curl' where name = 'Ayakta Barbell Biceps Curl';
update public.exercises set video_slug = 'standing-barbell-calf-raise' where name = 'Ayakta Barbell Calf Raise';
update public.exercises set video_slug = 'standing-barbell-shoulder-press' where name = 'Ayakta Barbell Omuz Press';
update public.exercises set video_slug = 'standing-barbell-triceps-extension' where name = 'Ayakta Barbell Triceps Extension';
update public.exercises set video_slug = 'standing-cable-biceps-curl' where name = 'Ayakta Cable Biceps Curl';
update public.exercises set video_slug = 'standing-cable-hammer-curl' where name = 'Ayakta Cable Hammer Curl';
update public.exercises set video_slug = 'standing-cable-triceps-extension' where name = 'Ayakta Cable Triceps Extension';
update public.exercises set video_slug = 'standing-dumbbell-biceps-curl' where name = 'Ayakta Dumbbell Biceps Curl';
update public.exercises set video_slug = 'standing-dumbbell-calf-raise' where name = 'Ayakta Dumbbell Calf Raise';
update public.exercises set video_slug = 'standing-dumbbell-hammer-curl' where name = 'Ayakta Dumbbell Hammer Curl';
update public.exercises set video_slug = 'standing-dumbbell-shoulder-press' where name = 'Ayakta Dumbbell Omuz Press';
update public.exercises set video_slug = 'standing-dumbbell-triceps-extension' where name = 'Ayakta Dumbbell Triceps Extension';
update public.exercises set video_slug = 'standing-ez-bar-biceps-curl' where name = 'Ayakta EZ Bar Biceps Curl';
update public.exercises set video_slug = 'standing-ez-bar-triceps-extension' where name = 'Ayakta EZ Bar Triceps Extension';
update public.exercises set video_slug = 'standing-makine-biceps-curl' where name = 'Ayakta Makine Biceps Curl';
update public.exercises set video_slug = 'standing-makine-calf-raise' where name = 'Ayakta Makine Calf Raise';
update public.exercises set video_slug = 'standing-makine-leg-curl' where name = 'Ayakta Makine Leg Curl';
update public.exercises set video_slug = 'standing-makine-shoulder-press' where name = 'Ayakta Makine Omuz Press';
update public.exercises set video_slug = 'standing-smith-machine-calf-raise' where name = 'Ayakta Smith Machine Calf Raise';
update public.exercises set video_slug = 'standing-smith-machine-shoulder-press' where name = 'Ayakta Smith Machine Omuz Press';
update public.exercises set video_slug = 'standing-calf-raise' where name = 'Ayakta Vücut Ağırlığı Calf Raise';
update public.exercises set video_slug = 'b-skip' where name = 'B-Skip';
update public.exercises set video_slug = 'leg-circles' where name = 'Bacak Daireleri';
update public.exercises set video_slug = 'leg-raise' where name = 'Bacak Kaldırma';
update public.exercises set video_slug = 'leg-swings' where name = 'Bacak Salınımı';
update public.exercises set video_slug = 'calf-stretch' where name = 'Baldır Esnetme';
update public.exercises set video_slug = 'calf-foam-rolling' where name = 'Baldır Foam Roller';
update public.exercises set video_slug = 'band-pull-apart' where name = 'Band Pull Apart';
update public.exercises set video_slug = 'barbell-wrist-curl' where name = 'Barbell Bilek Curl';
update public.exercises set video_slug = 'barbell-deadlift' where name = 'Barbell Deadlift';
update public.exercises set video_slug = 'barbell-good-morning' where name = 'Barbell Good Morning';
update public.exercises set video_slug = 'barbell-hip-thrust' where name = 'Barbell Hip Thrust';
update public.exercises set video_slug = 'barbell-landmine-press' where name = 'Barbell Landmine Press';
update public.exercises set video_slug = 'barbell-lunge' where name = 'Barbell Lunge';
update public.exercises set video_slug = 'barbell-pendlay-row' where name = 'Barbell Pendlay Row';
update public.exercises set video_slug = 'barbell-reverse-curl' where name = 'Barbell Reverse Curl';
update public.exercises set video_slug = 'barbell-romanian-deadlift' where name = 'Barbell Romanian Deadlift';
update public.exercises set video_slug = 'barbell-shrug' where name = 'Barbell Shrug';
update public.exercises set video_slug = 'barbell-split-squat' where name = 'Barbell Split Squat';
update public.exercises set video_slug = 'barbell-squat' where name = 'Barbell Squat';
update public.exercises set video_slug = 'barbell-step-up' where name = 'Barbell Step-Up';
update public.exercises set video_slug = 'barbell-t-bar-row' where name = 'Barbell T-Bar Row';
update public.exercises set video_slug = 'barbell-triceps-extension' where name = 'Barbell Triceps Extension';
update public.exercises set video_slug = 'barbell-upright-row' where name = 'Barbell Upright Row';
update public.exercises set video_slug = 'hanging-leg-raise' where name = 'Barfiks Barı Bacak Kaldırma';
update public.exercises set video_slug = 'pull-up' where name = 'Barfiks Barı Barfiks';
update public.exercises set video_slug = 'battle-rope' where name = 'Battle Rope';
update public.exercises set video_slug = 'lower-back-stretch' where name = 'Bel Esnetme';
update public.exercises set video_slug = 'bird-dog' where name = 'Bird Dog';
update public.exercises set video_slug = 'bicycle-crunch' where name = 'Bisiklet Mekiği';
update public.exercises set video_slug = 'bosu-balance' where name = 'Bosu Denge';
update public.exercises set video_slug = 'bounding' where name = 'Bounding';
update public.exercises set video_slug = 'neck-cars' where name = 'Boyun CARs';
update public.exercises set video_slug = 'neck-extension' where name = 'Boyun Ekstansiyon';
update public.exercises set video_slug = 'neck-stretch' where name = 'Boyun Esnetme';
update public.exercises set video_slug = 'neck-flexion' where name = 'Boyun Fleksiyon';
update public.exercises set video_slug = 'neck-lateral-flexion' where name = 'Boyun Lateral Fleksiyon';
update public.exercises set video_slug = 'neck-trigger-point-release' where name = 'Boyun Tetik Nokta';
update public.exercises set video_slug = 'bulgarian-barbell-lunge' where name = 'Bulgar Barbell Lunge';
update public.exercises set video_slug = 'bulgarian-barbell-split-squat' where name = 'Bulgar Barbell Split Squat';
update public.exercises set video_slug = 'bulgarian-dumbbell-lunge' where name = 'Bulgar Dumbbell Lunge';
update public.exercises set video_slug = 'bulgarian-dumbbell-split-squat' where name = 'Bulgar Dumbbell Split Squat';
update public.exercises set video_slug = 'bulgarian-kettlebell-lunge' where name = 'Bulgar Kettlebell Lunge';
update public.exercises set video_slug = 'bulgarian-lunge' where name = 'Bulgar Vücut Ağırlığı Lunge';
update public.exercises set video_slug = 'bulgarian-bodyweight-split-squat' where name = 'Bulgar Vücut Ağırlığı Split Squat';
update public.exercises set video_slug = 'cable-rear-delt-fly' where name = 'Cable Arka Omuz Fly';
update public.exercises set video_slug = 'cable-cable-crossover' where name = 'Cable Cable Crossover';
update public.exercises set video_slug = 'cable-cable-pull-through' where name = 'Cable Cable Pull-Through';
update public.exercises set video_slug = 'cable-cable-woodchop' where name = 'Cable Cable Woodchop';
update public.exercises set video_slug = 'cable-concentration-curl' where name = 'Cable Concentration Curl';
update public.exercises set video_slug = 'cable-crunch' where name = 'Cable Crunch';
update public.exercises set video_slug = 'cable-external-rotation' where name = 'Cable Dış Rotasyon';
update public.exercises set video_slug = 'cable-straight-arm-pulldown' where name = 'Cable Düz Kol Pulldown';
update public.exercises set video_slug = 'cable-face-pull' where name = 'Cable Face Pull';
update public.exercises set video_slug = 'cable-front-raise' where name = 'Cable Front Raise';
update public.exercises set video_slug = 'cable-glute-kickback' where name = 'Cable Glute Kickback';
update public.exercises set video_slug = 'cable-hip-abduction' where name = 'Cable Kalça Abdüksiyon';
update public.exercises set video_slug = 'cable-hip-adduction' where name = 'Cable Kalça Addüksiyon';
update public.exercises set video_slug = 'cable-lat-pulldown' where name = 'Cable Lat Pulldown';
update public.exercises set video_slug = 'cable-pullover' where name = 'Cable Pullover';
update public.exercises set video_slug = 'cable-reverse-curl' where name = 'Cable Reverse Curl';
update public.exercises set video_slug = 'cable-row' where name = 'Cable Row';
update public.exercises set video_slug = 'cable-shrug' where name = 'Cable Shrug';
update public.exercises set video_slug = 'cable-triceps-extension' where name = 'Cable Triceps Extension';
update public.exercises set video_slug = 'cable-triceps-pushdown' where name = 'Cable Triceps Pushdown';
update public.exercises set video_slug = 'cable-upright-row' where name = 'Cable Upright Row';
update public.exercises set video_slug = 'cross-crawl' where name = 'Çapraz Koordinasyon';
update public.exercises set video_slug = 'chin-tuck' where name = 'Çene İçeri Çekme';
update public.exercises set video_slug = 'dual-task-exercise' where name = 'Çift Görev Egzersizi';
update public.exercises set video_slug = 'farmer-s-carry' where name = 'Çiftçi Taşıması';
update public.exercises set video_slug = 'clamshell' where name = 'Clamshell';
update public.exercises set video_slug = 'clean-and-jerk' where name = 'Clean and Jerk';
update public.exercises set video_slug = 'child-s-pose' where name = 'Çocuk Pozu';
update public.exercises set video_slug = 'copenhagen-plank' where name = 'Copenhagen Plank';
update public.exercises set video_slug = 'mountain-climber' where name = 'Dağcı';
update public.exercises set video_slug = 'close-grip-barbell-bench-press' where name = 'Dar Tutuş Barbell Bench Press';
update public.exercises set video_slug = 'close-grip-barbell-row' where name = 'Dar Tutuş Barbell Row';
update public.exercises set video_slug = 'close-grip-barbell-t-bar-row' where name = 'Dar Tutuş Barbell T-Bar Row';
update public.exercises set video_slug = 'close-grip-pull-up' where name = 'Dar Tutuş Barfiks Barı Barfiks';
update public.exercises set video_slug = 'close-grip-cable-lat-pulldown' where name = 'Dar Tutuş Cable Lat Pulldown';
update public.exercises set video_slug = 'close-grip-cable-row' where name = 'Dar Tutuş Cable Row';
update public.exercises set video_slug = 'close-grip-cable-triceps-pushdown' where name = 'Dar Tutuş Cable Triceps Pushdown';
update public.exercises set video_slug = 'close-grip-resistance-band-triceps-pushdown' where name = 'Dar Tutuş Direnç Bandı Triceps Pushdown';
update public.exercises set video_slug = 'close-grip-dumbbell-bench-press' where name = 'Dar Tutuş Dumbbell Bench Press';
update public.exercises set video_slug = 'close-grip-dumbbell-row' where name = 'Dar Tutuş Dumbbell Row';
update public.exercises set video_slug = 'close-grip-makine-lat-pulldown' where name = 'Dar Tutuş Makine Lat Pulldown';
update public.exercises set video_slug = 'close-grip-makine-leg-press' where name = 'Dar Tutuş Makine Leg Press';
update public.exercises set video_slug = 'close-grip-makine-row' where name = 'Dar Tutuş Makine Row';
update public.exercises set video_slug = 'close-grip-makine-t-bar-row' where name = 'Dar Tutuş Makine T-Bar Row';
update public.exercises set video_slug = 'close-grip-smith-machine-bench-press' where name = 'Dar Tutuş Smith Machine Bench Press';
update public.exercises set video_slug = 'close-grip-push-up' where name = 'Dar Tutuş Vücut Ağırlığı Şınav';
update public.exercises set video_slug = 'dead-bug' where name = 'Dead Bug';
update public.exercises set video_slug = 'deficit-barbell-deadlift' where name = 'Deficit Barbell Deadlift';
update public.exercises set video_slug = 'depth-jump' where name = 'Derinlik Sıçraması';
update public.exercises set video_slug = 'diamond-push-up' where name = 'Diamond Şınav';
update public.exercises set video_slug = 'dips' where name = 'Dips';
update public.exercises set video_slug = 'resistance-band-pull-through' where name = 'Direnç Bandı Cable Pull-Through';
update public.exercises set video_slug = 'resistance-band-woodchop' where name = 'Direnç Bandı Cable Woodchop';
update public.exercises set video_slug = 'resistance-band-cuban-press' where name = 'Direnç Bandı Cuban Press';
update public.exercises set video_slug = 'resistance-band-external-rotation' where name = 'Direnç Bandı Dış Rotasyon';
update public.exercises set video_slug = 'tuck-jump' where name = 'Diz Çekme Sıçraması';
update public.exercises set video_slug = 'resistance-band-straight-arm-pulldown' where name = 'Direnç Bandı Düz Kol Pulldown';
update public.exercises set video_slug = 'resistance-band-face-pull' where name = 'Direnç Bandı Face Pull';
update public.exercises set video_slug = 'resistance-band-front-raise' where name = 'Direnç Bandı Front Raise';
update public.exercises set video_slug = 'resistance-band-glute-kickback' where name = 'Direnç Bandı Glute Kickback';
update public.exercises set video_slug = 'resistance-band-hip-abduction' where name = 'Direnç Bandı Kalça Abdüksiyon';
update public.exercises set video_slug = 'resistance-band-hip-adduction' where name = 'Direnç Bandı Kalça Addüksiyon';
update public.exercises set video_slug = 'resistance-band-tibialis-raise' where name = 'Direnç Bandı Tibialis Raise';
update public.exercises set video_slug = 'resistance-band-triceps-pushdown' where name = 'Direnç Bandı Triceps Pushdown';
update public.exercises set video_slug = 'diaphragmatic-breathing' where name = 'Diyafram Nefesi';
update public.exercises set video_slug = 'knee-to-chest' where name = 'Diz Göğse Çekme';
update public.exercises set video_slug = 'double-under' where name = 'Double Under';
update public.exercises set video_slug = 'dumbbell-rear-delt-fly' where name = 'Dumbbell Arka Omuz Fly';
update public.exercises set video_slug = 'dumbbell-wrist-curl' where name = 'Dumbbell Bilek Curl';
update public.exercises set video_slug = 'dumbbell-concentration-curl' where name = 'Dumbbell Concentration Curl';
update public.exercises set video_slug = 'dumbbell-cuban-press' where name = 'Dumbbell Cuban Press';
update public.exercises set video_slug = 'dumbbell-external-rotation' where name = 'Dumbbell Dış Rotasyon';
update public.exercises set video_slug = 'dumbbell-front-raise' where name = 'Dumbbell Front Raise';
update public.exercises set video_slug = 'dumbbell-hip-thrust' where name = 'Dumbbell Hip Thrust';
update public.exercises set video_slug = 'dumbbell-triceps-kickback' where name = 'Dumbbell Kickback';
update public.exercises set video_slug = 'dumbbell-lateral-raise' where name = 'Dumbbell Lateral Raise';
update public.exercises set video_slug = 'dumbbell-lunge' where name = 'Dumbbell Lunge';
update public.exercises set video_slug = 'dumbbell-bench-press' where name = 'Dumbbell Press';
update public.exercises set video_slug = 'dumbbell-pullover' where name = 'Dumbbell Pullover';
update public.exercises set video_slug = 'dumbbell-reverse-curl' where name = 'Dumbbell Reverse Curl';
update public.exercises set video_slug = 'dumbbell-romanian-deadlift' where name = 'Dumbbell Romanian Deadlift';
update public.exercises set video_slug = 'dumbbell-row' where name = 'Dumbbell Row';
update public.exercises set video_slug = 'dumbbell-russian-twist' where name = 'Dumbbell Rus Twist';
update public.exercises set video_slug = 'dumbbell-shrug' where name = 'Dumbbell Shrug';
update public.exercises set video_slug = 'frog-pump' where name = 'Frog Pump';
update public.exercises set video_slug = 'dumbbell-spider-curl' where name = 'Dumbbell Spider Curl';
update public.exercises set video_slug = 'dumbbell-split-squat' where name = 'Dumbbell Split Squat';
update public.exercises set video_slug = 'dumbbell-squat' where name = 'Dumbbell Squat';
update public.exercises set video_slug = 'dumbbell-step-up' where name = 'Dumbbell Step-Up';
update public.exercises set video_slug = 'dumbbell-triceps-extension' where name = 'Dumbbell Triceps Extension';
update public.exercises set video_slug = 'dumbbell-upright-row' where name = 'Dumbbell Upright Row';
update public.exercises set video_slug = 'paused-barbell-squat' where name = 'Duraklamalı Barbell Squat';
update public.exercises set video_slug = 'paused-dumbbell-squat' where name = 'Duraklamalı Dumbbell Squat';
update public.exercises set video_slug = 'paused-kettlebell-squat' where name = 'Duraklamalı Kettlebell Squat';
update public.exercises set video_slug = 'paused-smith-machine-squat' where name = 'Duraklamalı Smith Machine Squat';
update public.exercises set video_slug = 'wall-angel' where name = 'Duvar Meleği';
update public.exercises set video_slug = 'flat-barbell-bench-press' where name = 'Düz Barbell Bench Press';
update public.exercises set video_slug = 'flat-cable-chest-fly' where name = 'Düz Cable Göğüs Fly';
update public.exercises set video_slug = 'flat-dumbbell-bench-press' where name = 'Düz Dumbbell Bench Press';
update public.exercises set video_slug = 'flat-dumbbell-chest-fly' where name = 'Düz Dumbbell Göğüs Fly';
update public.exercises set video_slug = 'flat-makine-chest-fly' where name = 'Düz Makine Göğüs Fly';
update public.exercises set video_slug = 'flat-smith-machine-bench-press' where name = 'Düz Smith Machine Bench Press';
update public.exercises set video_slug = 'incline-barbell-bench-press' where name = 'Eğik Barbell Bench Press';
update public.exercises set video_slug = 'incline-barbell-biceps-curl' where name = 'Eğik Barbell Biceps Curl';
update public.exercises set video_slug = 'incline-cable-biceps-curl' where name = 'Eğik Cable Biceps Curl';
update public.exercises set video_slug = 'incline-cable-cable-crossover' where name = 'Eğik Cable Cable Crossover';
update public.exercises set video_slug = 'incline-cable-chest-fly' where name = 'Eğik Cable Göğüs Fly';
update public.exercises set video_slug = 'incline-dumbbell-bench-press' where name = 'Eğik Dumbbell Bench Press';
update public.exercises set video_slug = 'incline-dumbbell-biceps-curl' where name = 'Eğik Dumbbell Biceps Curl';
update public.exercises set video_slug = 'incline-dumbbell-chest-fly' where name = 'Eğik Dumbbell Göğüs Fly';
update public.exercises set video_slug = 'glute-foam-rolling' where name = 'Glute Foam Roller';
update public.exercises set video_slug = 'incline-ez-bar-biceps-curl' where name = 'Eğik EZ Bar Biceps Curl';
update public.exercises set video_slug = 'incline-makine-biceps-curl' where name = 'Eğik Makine Biceps Curl';
update public.exercises set video_slug = 'incline-makine-chest-fly' where name = 'Eğik Makine Göğüs Fly';
update public.exercises set video_slug = 'incline-smith-machine-bench-press' where name = 'Eğik Smith Machine Bench Press';
update public.exercises set video_slug = 'incline-push-up' where name = 'Eğik Vücut Ağırlığı Şınav';
update public.exercises set video_slug = 'elliptical' where name = 'Eliptik';
update public.exercises set video_slug = 'ez-bar-reverse-curl' where name = 'EZ Bar Reverse Curl';
update public.exercises set video_slug = 'ez-bar-spider-curl' where name = 'EZ Bar Spider Curl';
update public.exercises set video_slug = 'ez-bar-triceps-extension' where name = 'EZ Bar Triceps Extension';
update public.exercises set video_slug = 'wide-grip-barbell-row' where name = 'Geniş Tutuş Barbell Row';
update public.exercises set video_slug = 'wide-grip-barbell-t-bar-row' where name = 'Geniş Tutuş Barbell T-Bar Row';
update public.exercises set video_slug = 'wide-grip-barbell-upright-row' where name = 'Geniş Tutuş Barbell Upright Row';
update public.exercises set video_slug = 'wide-grip-pull-up' where name = 'Geniş Tutuş Barfiks Barı Barfiks';
update public.exercises set video_slug = 'wide-grip-cable-lat-pulldown' where name = 'Geniş Tutuş Cable Lat Pulldown';
update public.exercises set video_slug = 'wide-grip-cable-row' where name = 'Geniş Tutuş Cable Row';
update public.exercises set video_slug = 'wide-grip-cable-upright-row' where name = 'Geniş Tutuş Cable Upright Row';
update public.exercises set video_slug = 'wide-grip-dumbbell-row' where name = 'Geniş Tutuş Dumbbell Row';
update public.exercises set video_slug = 'glute-trigger-point-release' where name = 'Glute Tetik Nokta';
update public.exercises set video_slug = 'wide-grip-dumbbell-upright-row' where name = 'Geniş Tutuş Dumbbell Upright Row';
update public.exercises set video_slug = 'wide-grip-makine-lat-pulldown' where name = 'Geniş Tutuş Makine Lat Pulldown';
update public.exercises set video_slug = 'wide-grip-makine-leg-press' where name = 'Geniş Tutuş Makine Leg Press';
update public.exercises set video_slug = 'wide-grip-makine-row' where name = 'Geniş Tutuş Makine Row';
update public.exercises set video_slug = 'wide-grip-makine-t-bar-row' where name = 'Geniş Tutuş Makine T-Bar Row';
update public.exercises set video_slug = 'wide-grip-push-up' where name = 'Geniş Tutuş Vücut Ağırlığı Şınav';
update public.exercises set video_slug = 'glute-bridge' where name = 'Glute Bridge';
update public.exercises set video_slug = 'glute-bridge' where name = 'Glute Bridge Aktivasyon';
update public.exercises set video_slug = 'glute-stretch' where name = 'Glute Esnetme';
update public.exercises set video_slug = 'goblet-squat' where name = 'Goblet Squat';
update public.exercises set video_slug = 'chest-stretch' where name = 'Göğüs Esnetme';
update public.exercises set video_slug = 'pec-trigger-point-release' where name = 'Göğüs Tetik Nokta';
update public.exercises set video_slug = 'vision-focus-drill' where name = 'Görsel Odak Drilli';
update public.exercises set video_slug = 'trunk-rotation' where name = 'Gövde Rotasyonu';
update public.exercises set video_slug = 'sun-salutation' where name = 'Güneşe Selam';
update public.exercises set video_slug = 'pigeon-pose' where name = 'Güvercin Pozu';
update public.exercises set video_slug = 'light-jog' where name = 'Hafif Jog';
update public.exercises set video_slug = 'hamstring-stretch' where name = 'Hamstring Esnetme';
update public.exercises set video_slug = 'hamstring-foam-rolling' where name = 'Hamstring Foam Roller';
update public.exercises set video_slug = 'handstand' where name = 'Handstand';
update public.exercises set video_slug = 'hang-clean' where name = 'Hang Clean';
update public.exercises set video_slug = 'high-pull' where name = 'High Pull';
update public.exercises set video_slug = 'barbell-hip-thrust' where name = 'Hip Thrust';
update public.exercises set video_slug = 'internal-rotation' where name = 'İç Rotasyon';
update public.exercises set video_slug = 'it-band-foam-rolling' where name = 'IT Bandı Foam Roller';
update public.exercises set video_slug = 'jumping-jack' where name = 'Jumping Jack';
update public.exercises set video_slug = 'jumping-jacks-warm-up' where name = 'Jumping Jack Isınma';
update public.exercises set video_slug = 'hip-flexor-stretch' where name = 'Kalça Fleksör Esnetme';
update public.exercises set video_slug = 'hip-flexor-mobilization' where name = 'Kalça Fleksör Mobilizasyonu';
update public.exercises set video_slug = 'cat-cow' where name = 'Kedi-Deve';
update public.exercises set video_slug = 'rowing-machine' where name = 'Kürek Makinesi';
update public.exercises set video_slug = 'kettlebell-lunge' where name = 'Kettlebell Lunge';
update public.exercises set video_slug = 'kettlebell-romanian-deadlift' where name = 'Kettlebell Romanian Deadlift';
update public.exercises set video_slug = 'kettlebell-russian-twist' where name = 'Kettlebell Rus Twist';
update public.exercises set video_slug = 'kettlebell-squat' where name = 'Kettlebell Squat';
update public.exercises set video_slug = 'kettlebell-swing' where name = 'Kettlebell Swing';
update public.exercises set video_slug = 'sled-drag' where name = 'Kızak Çekme';
update public.exercises set video_slug = 'sled-push' where name = 'Kızak İtme';
update public.exercises set video_slug = 'cobra-pose' where name = 'Kobra';
update public.exercises set video_slug = 'bridge-pose' where name = 'Köprü Pozu';
update public.exercises set video_slug = 'swan' where name = 'Kuğu (Swan)';
update public.exercises set video_slug = 'box-breathing' where name = 'Kutu Nefesi';
update public.exercises set video_slug = 'l-sit' where name = 'L-Sit';
update public.exercises set video_slug = 'tire-flip' where name = 'Lastik Çevirme';
update public.exercises set video_slug = 'lat-stretch' where name = 'Lat Esnetme';
update public.exercises set video_slug = 'lat-foam-rolling' where name = 'Lat Foam Roller';
update public.exercises set video_slug = 'lateral-band-walk' where name = 'Lateral Band Yürüyüş';
update public.exercises set video_slug = 'dumbbell-lateral-raise' where name = 'Lateral Raise';
update public.exercises set video_slug = 'log-press' where name = 'Log Press';
update public.exercises set video_slug = 'makine-rear-delt-fly' where name = 'Makine Arka Omuz Fly';
update public.exercises set video_slug = 'makine-crunch' where name = 'Makine Crunch';
update public.exercises set video_slug = 'makine-glute-kickback' where name = 'Makine Glute Kickback';
update public.exercises set video_slug = 'makine-hack-squat' where name = 'Makine Hack Squat';
update public.exercises set video_slug = 'makine-hip-thrust' where name = 'Makine Hip Thrust';
update public.exercises set video_slug = 'makine-hip-abduction' where name = 'Makine Kalça Abdüksiyon';
update public.exercises set video_slug = 'makine-hip-adduction' where name = 'Makine Kalça Addüksiyon';
update public.exercises set video_slug = 'makine-lat-pulldown' where name = 'Makine Lat Pulldown';
update public.exercises set video_slug = 'makine-lateral-raise' where name = 'Makine Lateral Raise';
update public.exercises set video_slug = 'makine-leg-curl' where name = 'Makine Leg Curl';
update public.exercises set video_slug = 'makine-leg-extension' where name = 'Makine Leg Extension';
update public.exercises set video_slug = 'makine-leg-press' where name = 'Makine Leg Press';
update public.exercises set video_slug = 'makine-pec-deck' where name = 'Makine Pec Deck';
update public.exercises set video_slug = 'makine-row' where name = 'Makine Row';
update public.exercises set video_slug = 'makine-back-extension' where name = 'Makine Sırt Ekstansiyonu';
update public.exercises set video_slug = 'makine-t-bar-row' where name = 'Makine T-Bar Row';
update public.exercises set video_slug = 'agility-ladder-drill' where name = 'Merdiven Drilli';
update public.exercises set video_slug = 'stair-climber' where name = 'Merdiven Tırmanış';
update public.exercises set video_slug = 'monster-walk' where name = 'Monster Walk';
update public.exercises set video_slug = 'mountain-climber' where name = 'Mountain Climber';
update public.exercises set video_slug = 'muscle-up' where name = 'Muscle-Up';
update public.exercises set video_slug = 'nordic-curl-negative' where name = 'Nordic Curl Negatif';
update public.exercises set video_slug = 'nordic-hamstring-curl' where name = 'Nordic Hamstring';
update public.exercises set video_slug = 'neutral-grip-pull-up' where name = 'Nötr Tutuş Barfiks Barı Barfiks';
update public.exercises set video_slug = 'neutral-grip-cable-lat-pulldown' where name = 'Nötr Tutuş Cable Lat Pulldown';
update public.exercises set video_slug = 'neutral-grip-makine-lat-pulldown' where name = 'Nötr Tutuş Makine Lat Pulldown';
update public.exercises set video_slug = 'shoulder-cars' where name = 'Omuz CARs';
update public.exercises set video_slug = 'shoulder-trigger-point-release' where name = 'Omuz Tetik Nokta';
update public.exercises set video_slug = 'seated-barbell-biceps-curl' where name = 'Oturarak Barbell Biceps Curl';
update public.exercises set video_slug = 'seated-barbell-calf-raise' where name = 'Oturarak Barbell Calf Raise';
update public.exercises set video_slug = 'seated-barbell-landmine-press' where name = 'Oturarak Barbell Landmine Press';
update public.exercises set video_slug = 'seated-barbell-shoulder-press' where name = 'Oturarak Barbell Omuz Press';
update public.exercises set video_slug = 'seated-barbell-triceps-extension' where name = 'Oturarak Barbell Triceps Extension';
update public.exercises set video_slug = 'seated-cable-rear-delt-fly' where name = 'Oturarak Cable Arka Omuz Fly';
update public.exercises set video_slug = 'seated-cable-biceps-curl' where name = 'Oturarak Cable Biceps Curl';
update public.exercises set video_slug = 'seated-cable-hammer-curl' where name = 'Oturarak Cable Hammer Curl';
update public.exercises set video_slug = 'seated-cable-lateral-raise' where name = 'Oturarak Cable Lateral Raise';
update public.exercises set video_slug = 'seated-cable-triceps-extension' where name = 'Oturarak Cable Triceps Extension';
update public.exercises set video_slug = 'seated-dumbbell-rear-delt-fly' where name = 'Oturarak Dumbbell Arka Omuz Fly';
update public.exercises set video_slug = 'seated-dumbbell-biceps-curl' where name = 'Oturarak Dumbbell Biceps Curl';
update public.exercises set video_slug = 'seated-dumbbell-calf-raise' where name = 'Oturarak Dumbbell Calf Raise';
update public.exercises set video_slug = 'seated-dumbbell-hammer-curl' where name = 'Oturarak Dumbbell Hammer Curl';
update public.exercises set video_slug = 'seated-dumbbell-lateral-raise' where name = 'Oturarak Dumbbell Lateral Raise';
update public.exercises set video_slug = 'seated-dumbbell-shoulder-press' where name = 'Oturarak Dumbbell Omuz Press';
update public.exercises set video_slug = 'seated-dumbbell-triceps-extension' where name = 'Oturarak Dumbbell Triceps Extension';
update public.exercises set video_slug = 'seated-ez-bar-biceps-curl' where name = 'Oturarak EZ Bar Biceps Curl';
update public.exercises set video_slug = 'seated-ez-bar-triceps-extension' where name = 'Oturarak EZ Bar Triceps Extension';
update public.exercises set video_slug = 'seated-makine-rear-delt-fly' where name = 'Oturarak Makine Arka Omuz Fly';
update public.exercises set video_slug = 'seated-makine-biceps-curl' where name = 'Oturarak Makine Biceps Curl';
update public.exercises set video_slug = 'seated-makine-calf-raise' where name = 'Oturarak Makine Calf Raise';
update public.exercises set video_slug = 'seated-makine-lateral-raise' where name = 'Oturarak Makine Lateral Raise';
update public.exercises set video_slug = 'seated-makine-leg-curl' where name = 'Oturarak Makine Leg Curl';
update public.exercises set video_slug = 'seated-makine-shoulder-press' where name = 'Oturarak Makine Omuz Press';
update public.exercises set video_slug = 'seated-smith-machine-calf-raise' where name = 'Oturarak Smith Machine Calf Raise';
update public.exercises set video_slug = 'seated-smith-machine-shoulder-press' where name = 'Oturarak Smith Machine Omuz Press';
update public.exercises set video_slug = 'seated-calf-raise' where name = 'Oturarak Vücut Ağırlığı Calf Raise';
update public.exercises set video_slug = 'pallof-press' where name = 'Pallof Press';
update public.exercises set video_slug = 'pike-push-up' where name = 'Pike Şınav';
update public.exercises set video_slug = 'piriformis-stretch' where name = 'Piriformis Esnetme';
update public.exercises set video_slug = 'pistol-squat' where name = 'Pistol Squat';
update public.exercises set video_slug = 'pnf-adductor-stretch' where name = 'PNF Adductor Esnetme';
update public.exercises set video_slug = 'pnf-chest-stretch' where name = 'PNF Göğüs Esnetme';
update public.exercises set video_slug = 'pnf-hamstring-stretch' where name = 'PNF Hamstring Esnetme';
update public.exercises set video_slug = 'pnf-hip-stretch' where name = 'PNF Kalça Esnetme';
update public.exercises set video_slug = 'power-clean' where name = 'Power Clean';
update public.exercises set video_slug = 'preacher-barbell-biceps-curl' where name = 'Preacher Barbell Biceps Curl';
update public.exercises set video_slug = 'preacher-cable-biceps-curl' where name = 'Preacher Cable Biceps Curl';
update public.exercises set video_slug = 'preacher-dumbbell-biceps-curl' where name = 'Preacher Dumbbell Biceps Curl';
update public.exercises set video_slug = 'preacher-ez-bar-biceps-curl' where name = 'Preacher EZ Bar Biceps Curl';
update public.exercises set video_slug = 'preacher-makine-biceps-curl' where name = 'Preacher Makine Biceps Curl';
update public.exercises set video_slug = 'prone-y-raise' where name = 'Prone Y Raise';
update public.exercises set video_slug = 'push-press' where name = 'Push Press';
update public.exercises set video_slug = 'quadriceps-stretch' where name = 'Quadriceps Esnetme';
update public.exercises set video_slug = 'quad-foam-rolling' where name = 'Quadriceps Foam Roller';
update public.exercises set video_slug = 'reaction-drill' where name = 'Reaksiyon Drilli';
update public.exercises set video_slug = 'roll-up' where name = 'Roll-Up';
update public.exercises set video_slug = 'romanian-deadlift' where name = 'Romanian Deadlift';
update public.exercises set video_slug = 'stationary-bike' where name = 'Sabit Bisiklet';
update public.exercises set video_slug = 'warrior-i' where name = 'Savaşçı I';
update public.exercises set video_slug = 'warrior-ii' where name = 'Savaşçı II';
update public.exercises set video_slug = 'scapular-retraction' where name = 'Scapular Retraksiyon';
update public.exercises set video_slug = 'jumping-lunge' where name = 'Sıçrayarak Lunge';
update public.exercises set video_slug = 'upper-back-foam-rolling' where name = 'Sırt Foam Roller';
update public.exercises set video_slug = 'supine-spinal-twist' where name = 'Sırtüstü Omurga Rotasyonu';
update public.exercises set video_slug = 'sissy-squat' where name = 'Sissy Squat';
update public.exercises set video_slug = 'smith-machine-shrug' where name = 'Smith Machine Shrug';
update public.exercises set video_slug = 'smith-machine-squat' where name = 'Smith Machine Squat';
update public.exercises set video_slug = 'snatch' where name = 'Snatch';
update public.exercises set video_slug = 'sprint' where name = 'Sprint';
update public.exercises set video_slug = 'jump-squat' where name = 'Squat Sıçrama';
update public.exercises set video_slug = 'superman' where name = 'Superman';
update public.exercises set video_slug = 'tandem-stance' where name = 'Tandem Duruş';
update public.exercises set video_slug = 'teaser' where name = 'Teaser';
update public.exercises set video_slug = 'single-leg-balance' where name = 'Tek Ayak Denge';
update public.exercises set video_slug = 'single-leg-barbell-calf-raise' where name = 'Tek Bacak Barbell Calf Raise';
update public.exercises set video_slug = 'single-leg-barbell-hip-thrust' where name = 'Tek Bacak Barbell Hip Thrust';
update public.exercises set video_slug = 'single-leg-barbell-lunge' where name = 'Tek Bacak Barbell Lunge';
update public.exercises set video_slug = 'single-leg-barbell-romanian-deadlift' where name = 'Tek Bacak Barbell Romanian Deadlift';
update public.exercises set video_slug = 'single-leg-dumbbell-calf-raise' where name = 'Tek Bacak Dumbbell Calf Raise';
update public.exercises set video_slug = 'single-leg-dumbbell-hip-thrust' where name = 'Tek Bacak Dumbbell Hip Thrust';
update public.exercises set video_slug = 'single-leg-dumbbell-lunge' where name = 'Tek Bacak Dumbbell Lunge';
update public.exercises set video_slug = 'single-leg-dumbbell-romanian-deadlift' where name = 'Tek Bacak Dumbbell Romanian Deadlift';
update public.exercises set video_slug = 'single-leg-stretch' where name = 'Tek Bacak Germe';
update public.exercises set video_slug = 'single-leg-kettlebell-lunge' where name = 'Tek Bacak Kettlebell Lunge';
update public.exercises set video_slug = 'single-leg-kettlebell-romanian-deadlift' where name = 'Tek Bacak Kettlebell Romanian Deadlift';
update public.exercises set video_slug = 'single-leg-makine-calf-raise' where name = 'Tek Bacak Makine Calf Raise';
update public.exercises set video_slug = 'thruster' where name = 'Thruster';
update public.exercises set video_slug = 'single-leg-makine-hip-thrust' where name = 'Tek Bacak Makine Hip Thrust';
update public.exercises set video_slug = 'single-leg-makine-leg-curl' where name = 'Tek Bacak Makine Leg Curl';
update public.exercises set video_slug = 'single-leg-makine-leg-extension' where name = 'Tek Bacak Makine Leg Extension';
update public.exercises set video_slug = 'single-leg-rdl-balance' where name = 'Tek Bacak RDL Denge';
update public.exercises set video_slug = 'single-leg-smith-machine-calf-raise' where name = 'Tek Bacak Smith Machine Calf Raise';
update public.exercises set video_slug = 'single-leg-bodyweight-calf-raise' where name = 'Tek Bacak Vücut Ağırlığı Calf Raise';
update public.exercises set video_slug = 'single-leg-hip-thrust' where name = 'Tek Bacak Vücut Ağırlığı Hip Thrust';
update public.exercises set video_slug = 'single-leg-lunge' where name = 'Tek Bacak Vücut Ağırlığı Lunge';
update public.exercises set video_slug = 'single-leg-plank' where name = 'Tek Bacak Vücut Ağırlığı Plank';
update public.exercises set video_slug = 'single-arm-barbell-landmine-press' where name = 'Tek Kol Barbell Landmine Press';
update public.exercises set video_slug = 'single-arm-barbell-row' where name = 'Tek Kol Barbell Row';
update public.exercises set video_slug = 'single-arm-cable-triceps-kickback' where name = 'Tek Kol Cable Kickback';
update public.exercises set video_slug = 'single-arm-cable-lateral-raise' where name = 'Tek Kol Cable Lateral Raise';
update public.exercises set video_slug = 'single-arm-cable-row' where name = 'Tek Kol Cable Row';
update public.exercises set video_slug = 'single-arm-dumbbell-triceps-kickback' where name = 'Tek Kol Dumbbell Kickback';
update public.exercises set video_slug = 'single-arm-dumbbell-lateral-raise' where name = 'Tek Kol Dumbbell Lateral Raise';
update public.exercises set video_slug = 'single-arm-dumbbell-row' where name = 'Tek Kol Dumbbell Row';
update public.exercises set video_slug = 'single-arm-makine-lateral-raise' where name = 'Tek Kol Makine Lateral Raise';
update public.exercises set video_slug = 'single-arm-makine-row' where name = 'Tek Kol Makine Row';
update public.exercises set video_slug = 'single-arm-plank' where name = 'Tek Kol Vücut Ağırlığı Plank';
update public.exercises set video_slug = 'tempo-barbell-squat' where name = 'Tempolu Barbell Squat';
update public.exercises set video_slug = 'tempo-dumbbell-squat' where name = 'Tempolu Dumbbell Squat';
update public.exercises set video_slug = 'tempo-kettlebell-squat' where name = 'Tempolu Kettlebell Squat';
update public.exercises set video_slug = 'tempo-smith-machine-squat' where name = 'Tempolu Smith Machine Squat';
update public.exercises set video_slug = 'terminal-knee-extension' where name = 'Terminal Diz Ekstansiyonu';
update public.exercises set video_slug = 'reverse-barbell-wrist-curl' where name = 'Ters Barbell Bilek Curl';
update public.exercises set video_slug = 'reverse-barbell-deadlift' where name = 'Ters Barbell Deadlift';
update public.exercises set video_slug = 'reverse-barbell-lunge' where name = 'Ters Barbell Lunge';
update public.exercises set video_slug = 'reverse-cable-crunch' where name = 'Ters Cable Crunch';
update public.exercises set video_slug = 'reverse-cable-triceps-pushdown' where name = 'Ters Cable Triceps Pushdown';
update public.exercises set video_slug = 'reverse-resistance-band-triceps-pushdown' where name = 'Ters Direnç Bandı Triceps Pushdown';
update public.exercises set video_slug = 'reverse-dumbbell-wrist-curl' where name = 'Ters Dumbbell Bilek Curl';
update public.exercises set video_slug = 'reverse-dumbbell-lunge' where name = 'Ters Dumbbell Lunge';
update public.exercises set video_slug = 'decline-barbell-bench-press' where name = 'Ters Eğik Barbell Bench Press';
update public.exercises set video_slug = 'decline-cable-cable-crossover' where name = 'Ters Eğik Cable Cable Crossover';
update public.exercises set video_slug = 'crocodile-breathing' where name = 'Timsah Nefesi';
update public.exercises set video_slug = 'decline-dumbbell-bench-press' where name = 'Ters Eğik Dumbbell Bench Press';
update public.exercises set video_slug = 'decline-smith-machine-bench-press' where name = 'Ters Eğik Smith Machine Bench Press';
update public.exercises set video_slug = 'decline-push-up' where name = 'Ters Eğik Vücut Ağırlığı Şınav';
update public.exercises set video_slug = 'decline-sit-up' where name = 'Ters Eğik Vücut Ağırlığı Sit-Up';
update public.exercises set video_slug = 'reverse-kettlebell-lunge' where name = 'Ters Kettlebell Lunge';
update public.exercises set video_slug = 'reverse-makine-crunch' where name = 'Ters Makine Crunch';
update public.exercises set video_slug = 'reverse-crunch' where name = 'Ters Vücut Ağırlığı Crunch';
update public.exercises set video_slug = 'reverse-lunge' where name = 'Ters Vücut Ağırlığı Lunge';
update public.exercises set video_slug = 'toes-to-bar' where name = 'Toes-to-Bar';
update public.exercises set video_slug = 'ball-toss-and-catch' where name = 'Top Fırlatma-Yakalama';
update public.exercises set video_slug = 'thoracic-extension' where name = 'Torasik Ekstansiyon';
update public.exercises set video_slug = 'triceps-stretch' where name = 'Triceps Esnetme';
update public.exercises set video_slug = 'broad-jump' where name = 'Uzun Atlama';
update public.exercises set video_slug = 'leg-raise' where name = 'Vücut Ağırlığı Bacak Kaldırma';
update public.exercises set video_slug = 'crunch' where name = 'Vücut Ağırlığı Crunch';
update public.exercises set video_slug = 'hip-thrust' where name = 'Vücut Ağırlığı Hip Thrust';
update public.exercises set video_slug = 'lunge' where name = 'Vücut Ağırlığı Lunge';
update public.exercises set video_slug = 'plank' where name = 'Vücut Ağırlığı Plank';
update public.exercises set video_slug = 'bodyweight-russian-twist' where name = 'Vücut Ağırlığı Rus Twist';
update public.exercises set video_slug = 'push-up' where name = 'Vücut Ağırlığı Şınav';
update public.exercises set video_slug = 'back-extension' where name = 'Vücut Ağırlığı Sırt Ekstansiyonu';
update public.exercises set video_slug = 'sit-up' where name = 'Vücut Ağırlığı Sit-Up';
update public.exercises set video_slug = 'split-squat' where name = 'Vücut Ağırlığı Split Squat';
update public.exercises set video_slug = 'step-up' where name = 'Vücut Ağırlığı Step-Up';
update public.exercises set video_slug = 'tibialis-raise' where name = 'Vücut Ağırlığı Tibialis Raise';
update public.exercises set video_slug = 'wall-ball' where name = 'Wall Ball';
update public.exercises set video_slug = 'wall-slide' where name = 'Wall Slide';
update public.exercises set video_slug = 'side-plank' where name = 'Yan Plank';
update public.exercises set video_slug = 'marching-in-place' where name = 'Yerinde Yürüyüş';
update public.exercises set video_slug = 'ytw-raises' where name = 'YTW Kaldırış';
update public.exercises set video_slug = 'walking-lunge-stretch' where name = 'Yürüyen Lunge Esnemesi';
update public.exercises set video_slug = 'the-hundred' where name = 'Yüzlük (Hundred)';
update public.exercises set video_slug = 'the-hundred' where name = 'Pilates Hundred';
update public.exercises set video_slug = 'roll-up' where name = 'Roll Up';
update public.exercises set video_slug = 'roll-over' where name = 'Roll Over';
update public.exercises set video_slug = 'single-leg-circles' where name = 'Tek Bacak Daireleri';
update public.exercises set video_slug = 'rolling-like-a-ball' where name = 'Top Gibi Yuvarlanma';
update public.exercises set video_slug = 'double-leg-stretch' where name = 'Çift Bacak Germe';
update public.exercises set video_slug = 'single-straight-leg-stretch' where name = 'Makas (Pilates)';
update public.exercises set video_slug = 'double-straight-leg-stretch' where name = 'Çift Düz Bacak Germe';
update public.exercises set video_slug = 'criss-cross' where name = 'Criss Cross';
update public.exercises set video_slug = 'spine-stretch-forward' where name = 'Omurga Germe';
update public.exercises set video_slug = 'open-leg-rocker' where name = 'Açık Bacak Sallanma';
update public.exercises set video_slug = 'corkscrew' where name = 'Tirbuşon';
update public.exercises set video_slug = 'saw' where name = 'Testere';
update public.exercises set video_slug = 'swan-dive' where name = 'Kuğu Dalışı';
update public.exercises set video_slug = 'single-leg-kick' where name = 'Tek Bacak Tekme';
update public.exercises set video_slug = 'double-leg-kick' where name = 'Çift Bacak Tekme';
update public.exercises set video_slug = 'neck-pull' where name = 'Boyun Çekişi';
update public.exercises set video_slug = 'shoulder-bridge' where name = 'Omuz Köprüsü (Pilates)';
update public.exercises set video_slug = 'spine-twist' where name = 'Omurga Bükülmesi';
update public.exercises set video_slug = 'jackknife' where name = 'Jackknife';
update public.exercises set video_slug = 'side-kick-series' where name = 'Yan Tekme Serisi';
update public.exercises set video_slug = 'hip-circles' where name = 'Kalça Daireleri';
update public.exercises set video_slug = 'swimming' where name = 'Yüzme (Pilates)';
update public.exercises set video_slug = 'leg-pull-front' where name = 'Öne Bacak Çekişi';
update public.exercises set video_slug = 'leg-pull-back' where name = 'Arkaya Bacak Çekişi';
update public.exercises set video_slug = 'side-bend' where name = 'Yan Eğilme (Pilates)';
update public.exercises set video_slug = 'boomerang' where name = 'Bumerang';
update public.exercises set video_slug = 'seal' where name = 'Fok';
update public.exercises set video_slug = 'mermaid' where name = 'Deniz Kızı';
update public.exercises set video_slug = 'clam' where name = 'Midye (Clam)';
update public.exercises set video_slug = 'pilates-plank' where name = 'Pilates Plank';
update public.exercises set video_slug = 'pilates-side-plank' where name = 'Pilates Yan Plank';
update public.exercises set video_slug = 'piriformis-stretch' where name = 'Piriformis Germe';
update public.exercises set video_slug = 'toe-taps' where name = 'Ayak Parmağı Dokunuşu';
update public.exercises set video_slug = 'chest-lift' where name = 'Göğüs Kaldırma';
update public.exercises set video_slug = 'pelvic-curl' where name = 'Pelvik Kıvrılma';
update public.exercises set video_slug = 'table-top' where name = 'Masa Üstü Duruşu';
update public.exercises set video_slug = 'dead-bug' where name = 'Ölü Böcek';
update public.exercises set video_slug = 'bird-dog' where name = 'Kuş Köpek (Pilates)';
update public.exercises set video_slug = 'roll-down' where name = 'Omurga Aşağı Yuvarlama';
update public.exercises set video_slug = 'standing-roll-down' where name = 'Ayakta Roll Down';
update public.exercises set video_slug = 'heel-beats' where name = 'Topuk Vuruşları';
update public.exercises set video_slug = 'prone-leg-lifts' where name = 'Prone Bacak Kaldırma';
update public.exercises set video_slug = 'reformer-footwork' where name = 'Reformer Footwork';
update public.exercises set video_slug = 'reformer-elephant' where name = 'Reformer Elephant';
update public.exercises set video_slug = 'reformer-long-stretch' where name = 'Reformer Long Stretch';
update public.exercises set video_slug = 'reformer-short-box' where name = 'Reformer Short Box';
update public.exercises set video_slug = 'reformer-leg-circles' where name = 'Reformer Leg Circles';
update public.exercises set video_slug = 'mountain-pose-tadasana' where name = 'Dağ Duruşu';
update public.exercises set video_slug = 'upward-dog' where name = 'Yukarı Bakan Köpek';
update public.exercises set video_slug = 'child-s-pose' where name = 'Çocuk Duruşu';
update public.exercises set video_slug = 'cat-cow' where name = 'Kedi-İnek';
update public.exercises set video_slug = 'warrior-iii' where name = 'Savaşçı III';
update public.exercises set video_slug = 'triangle-pose' where name = 'Üçgen Duruşu';
update public.exercises set video_slug = 'tree-pose' where name = 'Ağaç Duruşu';
update public.exercises set video_slug = 'chair-pose' where name = 'Sandalye Duruşu';
update public.exercises set video_slug = 'bridge-pose' where name = 'Köprü Duruşu';
update public.exercises set video_slug = 'pigeon-pose' where name = 'Güvercin Duruşu';
update public.exercises set video_slug = 'bound-angle-pose' where name = 'Kelebek Duruşu';
update public.exercises set video_slug = 'boat-pose' where name = 'Tekne Duruşu';
update public.exercises set video_slug = 'camel-pose' where name = 'Deve Duruşu';
update public.exercises set video_slug = 'bow-pose' where name = 'Yay Duruşu';
update public.exercises set video_slug = 'locust-pose' where name = 'Çekirge Duruşu';
update public.exercises set video_slug = 'side-plank-vasisthasana' where name = 'Yan Plank (Yoga)';
update public.exercises set video_slug = 'eagle-pose' where name = 'Kartal Duruşu';
update public.exercises set video_slug = 'dancer-pose' where name = 'Dansçı Duruşu';
update public.exercises set video_slug = 'half-moon-pose' where name = 'Yarım Ay Duruşu';
update public.exercises set video_slug = 'standing-forward-fold' where name = 'Öne Eğilme';
update public.exercises set video_slug = 'seated-forward-bend' where name = 'Oturarak Öne Eğilme';
update public.exercises set video_slug = 'fish-pose' where name = 'Balık Duruşu';
update public.exercises set video_slug = 'low-lunge' where name = 'Alçak Hamle';
update public.exercises set video_slug = 'high-lunge' where name = 'Yüksek Hamle';
update public.exercises set video_slug = 'reverse-warrior' where name = 'Ters Savaşçı';
update public.exercises set video_slug = 'garland-pose-malasana' where name = 'Guyabani Duruşu';
update public.exercises set video_slug = 'crow-pose' where name = 'Karga Duruşu';
update public.exercises set video_slug = 'shoulder-stand' where name = 'Omuz Duruşu';
update public.exercises set video_slug = 'plow-pose' where name = 'Pulluk Duruşu';
update public.exercises set video_slug = 'thread-the-needle' where name = 'İğneden Geçirme';
update public.exercises set video_slug = 'sphinx-pose' where name = 'Sfenks Duruşu';
update public.exercises set video_slug = 'happy-baby' where name = 'Mutlu Bebek';
update public.exercises set video_slug = 'supine-twist' where name = 'Sırtüstü Bükülme';
update public.exercises set video_slug = 'lotus-pose' where name = 'Lotus Duruşu';
update public.exercises set video_slug = 'easy-pose' where name = 'Kolay Oturuş';
update public.exercises set video_slug = 'seated-twist' where name = 'Oturarak Bükülme';
update public.exercises set video_slug = 'sun-salutation-a' where name = 'Selamlama A';
update public.exercises set video_slug = 'sun-salutation-b' where name = 'Selamlama B';
update public.exercises set video_slug = 'gate-pose' where name = 'Kapı Duruşu';
update public.exercises set video_slug = 'head-to-knee-pose' where name = 'Baş-Diz Duruşu';
update public.exercises set video_slug = 'corpse-pose-savasana' where name = 'Şavasana';
update public.exercises set video_slug = 'world-s-greatest-stretch' where name = 'Dünyanın En İyi Germesi';
update public.exercises set video_slug = 'thoracic-rotation' where name = 'Torasik Rotasyon';
update public.exercises set video_slug = 'shoulder-dislocates' where name = 'Omuz Dislokasyonu (Çubuk)';
update public.exercises set video_slug = 'frog-stretch' where name = 'Kurbağa Germesi';
update public.exercises set video_slug = 'cossack-squat' where name = 'Cossack Squat';
update public.exercises set video_slug = 'deep-squat-hold' where name = 'Derin Squat Bekleme';
update public.exercises set video_slug = 'hip-cars' where name = 'Kalça CARs';
update public.exercises set video_slug = 'scapula-push-up' where name = 'Skapula Şınavı';
update public.exercises set video_slug = 'wall-slides' where name = 'Duvar Kaydırma';
update public.exercises set video_slug = 'prone-swimmers' where name = 'Prone Yüzücüler';
update public.exercises set video_slug = 'hip-airplane' where name = 'Kalça Uçağı';
update public.exercises set video_slug = 'leg-swings-front' where name = 'Öne Bacak Salınımı';
update public.exercises set video_slug = 'leg-swings-side' where name = 'Yana Bacak Salınımı';
update public.exercises set video_slug = 'arm-circles' where name = 'Kol Daireleri';
update public.exercises set video_slug = 'standing-side-bend' where name = 'Ayakta Yan Eğilme';
update public.exercises set video_slug = 'spiderman-lunge' where name = 'Spiderman Hamle';
update public.exercises set video_slug = 'groiners' where name = 'Groiners';
update public.exercises set video_slug = 'wrist-circles' where name = 'Bilek Daireleri';
update public.exercises set video_slug = 'couch-stretch' where name = 'Kanepe Germesi';
update public.exercises set video_slug = 'pancake-stretch' where name = 'Pancake Germesi';
update public.exercises set video_slug = 'jefferson-curl' where name = 'Jefferson Curl';
update public.exercises set video_slug = 'kettlebell-halo' where name = 'Kettlebell Halo';
update public.exercises set video_slug = 'bear-sit-rotation' where name = 'Ayı Oturuşu Rotasyonu';
update public.exercises set video_slug = 'hamstring-stretch' where name = 'Hamstring Germe';
update public.exercises set video_slug = 'quad-stretch' where name = 'Quadriceps Germe';
update public.exercises set video_slug = 'calf-stretch' where name = 'Baldır Germe';
update public.exercises set video_slug = 'hip-flexor-stretch' where name = 'Kalça Fleksör Germe';
update public.exercises set video_slug = 'doorway-chest-stretch' where name = 'Göğüs Germe (Kapı)';
update public.exercises set video_slug = 'triceps-stretch' where name = 'Triceps Germe';
update public.exercises set video_slug = 'cross-body-shoulder-stretch' where name = 'Omuz Çapraz Germe';
update public.exercises set video_slug = 'side-neck-stretch' where name = 'Boyun Yan Germe';
update public.exercises set video_slug = 'figure-4-stretch' where name = 'Figür 4 Germe';
update public.exercises set video_slug = 'butterfly-stretch' where name = 'Kelebek Germe';
update public.exercises set video_slug = 'seated-forward-reach' where name = 'Otur-Uzan Germe';
update public.exercises set video_slug = 'lat-stretch' where name = 'Lat Germe';
update public.exercises set video_slug = 'wrist-flexor-stretch' where name = 'Bilek Fleksör Germe';
update public.exercises set video_slug = 'wrist-extensor-stretch' where name = 'Bilek Ekstansör Germe';
update public.exercises set video_slug = 'adductor-stretch' where name = 'Adduktor Germe';
update public.exercises set video_slug = 'kneeling-hip-flexor-stretch' where name = 'Diz Üstü Kalça Germe';
update public.exercises set video_slug = 'levator-scapulae-stretch' where name = 'Levator Scapulae Germe';
update public.exercises set video_slug = 'overhead-triceps-stretch' where name = 'Overhead Triceps Germe';
update public.exercises set video_slug = 'wall-calf-stretch' where name = 'Duvar Baldır Germe';
update public.exercises set video_slug = 'runner-s-lunge-stretch' where name = 'Koşucu Hamlesi Germe';
update public.exercises set video_slug = 'cobra-stretch' where name = 'Kobra Germe';
update public.exercises set video_slug = 'lower-back-rotation-stretch' where name = 'Bel Rotasyon Germe';
update public.exercises set video_slug = 'neck-forward-stretch' where name = 'Boyun Öne Germe';
update public.exercises set video_slug = 'single-leg-stance' where name = 'Tek Ayak Duruşu';
update public.exercises set video_slug = 'single-leg-stance-eyes-closed' where name = 'Tek Ayak (Gözler Kapalı)';
update public.exercises set video_slug = 'bosu-squat' where name = 'Bosu Squat';
update public.exercises set video_slug = 'star-balance-y-reach' where name = 'Yıldız Denge';
update public.exercises set video_slug = 'single-leg-balance-deadlift' where name = 'Tek Ayak Deadlift (Denge)';
update public.exercises set video_slug = 'heel-to-toe-walk' where name = 'Topuk-Parmak Yürüyüş';
update public.exercises set video_slug = 'single-leg-reach' where name = 'Tek Ayak Uzanma';
update public.exercises set video_slug = 'airplane-balance' where name = 'Uçak Duruşu';
update public.exercises set video_slug = 'wobble-board-balance' where name = 'Wobble Board Denge';
update public.exercises set video_slug = 'single-leg-calf-raise' where name = 'Tek Ayak Kalf';
update public.exercises set video_slug = 'flamingo-hold' where name = 'Flamingo Duruşu';
update public.exercises set video_slug = 'single-leg-swing' where name = 'Tek Ayak Salınım';
update public.exercises set video_slug = 'bosu-plank' where name = 'Bosu Plank';
update public.exercises set video_slug = '4-7-8-breathing' where name = '4-7-8 Nefes';
update public.exercises set video_slug = 'alternate-nostril-breathing' where name = 'Alternatif Burun Nefesi';
update public.exercises set video_slug = 'deep-belly-breathing' where name = 'Derin Karın Nefesi';
update public.exercises set video_slug = 'extended-exhale-breathing' where name = 'Uzun Ekshalasyon';
update public.exercises set video_slug = 'wim-hof-breathing' where name = 'Wim Hof Nefesi';
update public.exercises set video_slug = 'relaxation-breath' where name = 'Rahatlama Nefesi';
update public.exercises set video_slug = 'diamond-push-up' where name = 'Elmas Şınav';
update public.exercises set video_slug = 'archer-push-up' where name = 'Archer Şınav';
update public.exercises set video_slug = 'hindu-push-up' where name = 'Hindu Şınav';
update public.exercises set video_slug = 'pseudo-planche-push-up' where name = 'Pseudo Planche Şınav';
update public.exercises set video_slug = 'wide-grip-pull-up' where name = 'Geniş Tutuş Barfiks';
update public.exercises set video_slug = 'close-grip-chin-up' where name = 'Dar Tutuş Barfiks';
update public.exercises set video_slug = 'commando-pull-up' where name = 'Komando Barfiks';
update public.exercises set video_slug = 'australian-row' where name = 'Avustralya Row';
update public.exercises set video_slug = 'muscle-up' where name = 'Muscle Up';
update public.exercises set video_slug = 'parallel-bar-dips' where name = 'Dips (Paralel)';
update public.exercises set video_slug = 'korean-dips' where name = 'Kore Dips';
update public.exercises set video_slug = 'tuck-planche' where name = 'Tuck Planche';
update public.exercises set video_slug = 'tuck-front-lever' where name = 'Tuck Front Lever';
update public.exercises set video_slug = 'wall-handstand-hold' where name = 'Duvar Handstand';
update public.exercises set video_slug = 'wall-handstand-push-up' where name = 'Handstand Şınav (Duvar)';
update public.exercises set video_slug = 'shrimp-squat' where name = 'Shrimp Squat';
update public.exercises set video_slug = 'nordic-hamstring-curl' where name = 'Nordic Curl';
update public.exercises set video_slug = 'hollow-body-hold' where name = 'Hollow Body Hold';
update public.exercises set video_slug = 'superman-hold' where name = 'Superman Hold';
update public.exercises set video_slug = 'v-up' where name = 'V-Up';
update public.exercises set video_slug = 'hanging-leg-raise' where name = 'Barfikste Bacak Kaldırma';
update public.exercises set video_slug = 'toes-to-bar' where name = 'Toes to Bar';
update public.exercises set video_slug = 'windshield-wipers' where name = 'Cam Sileceği';
update public.exercises set video_slug = 'human-flag-prep' where name = 'İnsan Bayrağı Hazırlık';
update public.exercises set video_slug = 'turkish-get-up' where name = 'Türk Kalkışı';
update public.exercises set video_slug = 'battle-ropes' where name = 'Battle Ropes';
update public.exercises set video_slug = 'sled-push' where name = 'Sled İtme';
update public.exercises set video_slug = 'farmer-s-carry' where name = 'Farmer Carry';
update public.exercises set video_slug = 'devil-press' where name = 'Devil Press';
update public.exercises set video_slug = 'man-maker' where name = 'Man Maker';
update public.exercises set video_slug = 'dead-ball-slam' where name = 'Dead Ball Slam';
update public.exercises set video_slug = 'sledgehammer-swing' where name = 'Balyoz Vuruşu';
update public.exercises set video_slug = 'sled-pull' where name = 'Sled Çekişi';
update public.exercises set video_slug = 'sandbag-clean' where name = 'Sandbag Clean';
update public.exercises set video_slug = 'sandbag-carry' where name = 'Sandbag Taşıma';
update public.exercises set video_slug = 'butt-kicks' where name = 'Topuk Vuruşu Koşu';
update public.exercises set video_slug = 'squat-jump' where name = 'Squat Jump';
update public.exercises set video_slug = 'tuck-jump' where name = 'Tuck Jump';
update public.exercises set video_slug = 'sprawl' where name = 'Sprawl';
update public.exercises set video_slug = 'lateral-bound' where name = 'Lateral Bound';
update public.exercises set video_slug = 'star-jump' where name = 'Star Jump';
update public.exercises set video_slug = 'fast-feet' where name = 'Fast Feet';
update public.exercises set video_slug = 'plank-jack' where name = 'Plank Jack';
update public.exercises set video_slug = 'broad-jump' where name = 'Broad Jump';

-- aliases: kullanıcının arayabileceği diğer yaygın adlar
update public.exercises set aliases = array['RDL','Romanian Barbell Deadlift']::text[] where english_name = 'Romanian Deadlift';
update public.exercises set aliases = array['Deadlift']::text[] where english_name = 'Conventional Deadlift';
update public.exercises set aliases = array['Barbell Squat','Squat']::text[] where english_name = 'Back Squat';
update public.exercises set aliases = array['Bench Press','Flat Bench Press']::text[] where english_name = 'Barbell Bench Press';
update public.exercises set aliases = array['DB Bench Press']::text[] where english_name = 'Dumbbell Bench Press';
update public.exercises set aliases = array['Pushup','Press-Up']::text[] where english_name = 'Push-Up';
update public.exercises set aliases = array['Pullup','Chin-Up']::text[] where english_name = 'Pull-Up';
update public.exercises set aliases = array['Situp']::text[] where english_name = 'Sit-Up';
update public.exercises set aliases = array['Pulldown']::text[] where english_name = 'Lat Pulldown';
update public.exercises set aliases = array['Hip Thrust']::text[] where english_name = 'Barbell Hip Thrust';
update public.exercises set aliases = array['Overhead Press','Shoulder Press']::text[] where english_name = 'Dumbbell Shoulder Press';
update public.exercises set aliases = array['Side Raise','Lateral Raise']::text[] where english_name = 'Dumbbell Lateral Raise';
update public.exercises set aliases = array['Biceps Curl','Dumbbell Curl']::text[] where english_name = 'Dumbbell Biceps Curl';
update public.exercises set aliases = array['Rear Foot Elevated Split Squat','RFESS']::text[] where english_name = 'Bulgarian Split Squat';
update public.exercises set aliases = array['Cable Pushdown','Tricep Pushdown']::text[] where english_name = 'Triceps Pushdown';
update public.exercises set aliases = array['Lying Leg Raise']::text[] where english_name = 'Leg Raise';
update public.exercises set aliases = array['Hip Bridge']::text[] where english_name = 'Glute Bridge';
update public.exercises set aliases = array['Cable Pushdown','Tricep Pushdown']::text[] where english_name = 'Triceps Pushdown';
update public.exercises set aliases = array['Lying Leg Raise']::text[] where english_name = 'Leg Raise';
update public.exercises set aliases = array['Hip Bridge']::text[] where english_name = 'Glute Bridge';

-- --- Arama: standart isim + alias üzerinden ------------------------------
-- Kullanıcı "RDL" yazınca Romanian Deadlift bulunmalı.
create index if not exists idx_exercises_english_name
  on public.exercises (lower(english_name));
create index if not exists idx_exercises_aliases
  on public.exercises using gin (aliases);
create index if not exists idx_exercises_video_slug
  on public.exercises (video_slug);
